### ISSUE TITLE
Crash with Sodium

### ISSUE THREAD

**Issue by Navota** [LambdAurora/LambDynamicLights#1]
Minecraft crashes with Sodiums smooth lighting setting on high when entering a world or setting it to high when ingame

[latest.log](https://github.com/LambdAurora/LambDynamicLights/files/4891867/latest.log)

**Comment by LambdAurora** [comment]
Hello!

I am already aware of the issue and the next release will fix that incompability, it should only happen with the latest build of Sodium.

**Comment by LambdAurora** [comment]
Fixed in latest release :3
https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights/files/2999843
