### ISSUE TITLE
Some weirdness with LamdDynamicLights

### ISSUE THREAD

**Issue by redstonerti** [LambdAurora/LambDynamicLights#101]
The drill bit of drills and the hand of deployers remain unlit while the rest of the block is lit. I don't know who's fault this is so i'm posting it on both githubs
![image](https://user-images.githubusercontent.com/48157961/158185346-0dee8248-8775-4c39-a5bc-629ba87aacea.png)
**Reproduction Steps**
get in a dark room
hold a torch
look at a drill

**Comment by bahdaniec** [comment]
Same problem on MacBook Pro 14 (M1 Pro)
Minecraft 1.20.1 
Mod version 2.3.1

**Comment by LambdAurora** [comment]
This should be fixed using the [Create: Dynamic Lights](https://modrinth.com/mod/create-dynamic-lights).
