### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by Probattler** [LambdAurora/LambDynamicLights#103]
**Description**
Whenever, I enter the nether with the dynamic lights on or specifically the ''entites'' option turned on inside it, it causes alot of lag spikes.

**To reproduce**
1. Go to Nether.
2. Turn on the dynamic lights or specially the ''entities'' option inside it.
3. Press alt+f3 and check the chart for lag spikes.

**Expected behaviour**
Simple dynamic lights.

**Screenshots**
[here](https://ibb.co/7XhVw0G)

**Desktop :**
 - OS: Linux/Ubuntu
 - Minecraft 1.16.5
 - Fabric Loader version 0.13.3
 -  [Mods](https://ibb.co/TkB3grf)
 - Version 1.3.4+1.16
 - Branch 1.16

**Comment by Kichura** [comment]
Can reproduce on other machines (Minus the ryzen 7 machine i own) where holding any light sources cause more lags than expected in some scenarios - disabling the mod fixes this somehow.

**Comment by TheRealJake12** [comment]
this also applys to 1.19.2

**Comment by TheRealJake12** [comment]
on windows

**Comment by Fnige** [comment]
Iirc this was talked about on her server before, try turning on "Always Defer Chunk Updates" within sodium settings and see if that helps

**Comment by TheRealJake12** [comment]
I always have ADCU on so idk it might just be my pc being weird

**Comment by srnyx** [comment]
> Iirc this was talked about on her server before, try turning on "Always Defer Chunk Updates" within sodium settings and see if that helps

This worked for me, thank you!
*Here are some spark reports I took in-case anyone wants to look into this bug:
https://spark.lucko.me/7ZlE3uNaNG (shaders enabled, 1.5 minutes)
https://spark.lucko.me/fUSl9dNmRG (shaders disabled, 15 seconds)*
