### ISSUE TITLE
Indistinguishable blocks on glow item frame.

### ISSUE THREAD

**Issue by Psychodeus** [LambdAurora/LambDynamicLights#106]
When I turn off the shaders the item attached on **glow item frame** is distinguishable.
![2022-04-27_03 57 48](https://user-images.githubusercontent.com/93028949/165382696-f8f00f24-0c97-41ab-adb3-55b06435f274.png)

But, if I turn on the shaders the item attached is so bright, it becomes indistinguishable.
![2022-04-27_03 58 00](https://user-images.githubusercontent.com/93028949/165382660-6c2423f6-2aac-4bbf-9a5f-425dfb956e3a.png)

Even if I turn off the **Glow item frame** from **Dynamic Light Sources: Entities**, it still indistinguishable.
![2022-04-27_04 06 23](https://user-images.githubusercontent.com/93028949/165383263-3d15aa7f-d4a0-4ed2-ba11-c4e6a9dbb5a7.png)

Perhaps, could you add options to "don't turn item attached on glow item frame as light source"?

**Comment by LambdAurora** [comment]
I'm not sure how that is actually related to the mod, since you mentioned that items are still hard to see when the option is turned off?

This seems to be a shader issue.

**Comment by Psychodeus** [comment]
Alright. I will find a way to config the shader then. I thought it was the mod messing with the shaders.
