### ISSUE TITLE
Configuration menu settings not saved

### ISSUE THREAD

**Issue by ghost** [LambdAurora/LambDynamicLights#107]
If you change the mod settings from the game menu, they are not applied and not saved. If you change the setting in the configuration file, everything works.

1. Go to mod menu
2. Select Lamb Dynamic Lights
3. Click on mod settings
4. Change default settings
5. Save settings

Steps to correct save settings
1. Go to %AppData%\.minecraft\config
2. Open .json mod config file in Notepad++
3. Change settings
4. Save file

Desktop
 - OS: Windows 10 64Bit 21H2
 - Minecraft 1.18.2
 - Fabric Loader 0.13.3
 - Mods: Fabric API 0.51.1, Cloth Config 6.2.57, Mod Menu 3.2.1, Lamb Dynamic Lights 2.1.0, Krypton 0.1.9, Ferrite Core 4.2.1, Lithium 0.7.9, Phosphor 0.8.1, Sodium 0.4.1, Indium 1.0.3, Enhanced Block Entities 0.6, Reborn Core 5.2.0 Beta 3, Tech Reborn 5.2.0 Beta 3
 - Version 2.1.0
 - Branch 1.18

**Comment by ghost** [comment]
I seem to have found a clarification, the settings began to be saved normally if you remove Reborn Core. I have a regularly changing modpack, I'll try to localize the incompatibility and possibly catch an error in the logs.

**Comment by LambdAurora** [comment]
I am unable to reproduce.
