### ISSUE TITLE
Mod flagged by antivirus as Trojan

### ISSUE THREAD

**Issue by Grandmaster-Jax** [LambdAurora/LambDynamicLights#108]
This mod is being flagged by my antivirus (Vipre) as a Trojan classed as java.trojan.GenericGBA.31525

To make sure that this was not a false flag I uploaded the mod to virustotal.
The mod itself does not get flagged as malicious. However the file lambdynamiclights-2.1.0+1.17.jar\dev\lambdaurora\lambdynlights\shadow\nightconfig\toml\tomlparser.class does get detected.

I have used this mod for a fair while and can only assume this is a false detection.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows/Linux Fedora
 - Minecraft 1.18.2
 - Fabric Loader version 0.13.3-1.18.2
 - Version 2.1.0+1.17

**Comment by LambdAurora** [comment]
Is this Windows Defender, *again*?

**Comment by Grandmaster-Jax** [comment]
I really do wonder sometimes if my AV is just a rewrite of Windows Defender, but unfortunately, no.
Here is the hash from virustotal
d69995fa3019af0b69dea1e1e1ed1dc769bd47c36b2bb68f6ccb809855c6c43d

**Comment by Grandmaster-Jax** [comment]
This file has been cleared and the flags identifying it as a Trojan have been corrected in the latest threat definitions
VirusTotal reflects these changes with only 1 false positive for McAfee. (No one should use McAfee anyway)
