### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by nijahplays** [LambdAurora/LambDynamicLights#109]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
1.19 support
**Describe alternatives you've considered**
None really

**Comment by Yoad1704** [comment]
> **Is your feature request related to a problem? Please describe.** No **Describe the solution you'd like** 1.19 support **Describe alternatives you've considered** None really

Um hi again lol saw u on another GitHub page but yeah I would love to see this mod in 1.19.

**Comment by LambdAurora** [comment]
[Welp, that's done](https://modrinth.com/mod/lambdynamiclights/version/2.1.2+1.19)

[CurseForge for those who prefer it](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights/files/3824820)

**Comment by nijahplays** [comment]
Thank you!
