### ISSUE TITLE
Game crashes when clicking "open resourcepacks folder" button

### ISSUE THREAD

**Issue by finskucode** [LambdAurora/LambDynamicLights#110]
**Describe the bug**
The game freezes completely if you click "open resource packs folder" and then crashes.

**To Reproduce**
1. Go to options -> resource packs
2. Click on 'Open pack folder'
3. Game freezes and crashes

**Expected behavior**
Opening the resource packs folder and NOT freezing and crashing.

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux]
 - Minecraft 1.19
 - Fabric Loader version 0.14.7
 - Mods: fabric-api v0.55.3+1.19, lambdynamiclights v2.1.2+1.19, modmenu v4.0.0, BetterF3 v1.3.1-Fabric-1.19, camerautils v.1.0.0-1.19, cem v0.7.1, CITResewn v1.1.0+1.19, cloth-config v7.0.69-fabric, colormatic v3.1.2+mc.1.19, continuity v2.0.0+1.19, dynamic-fps v2.1.0, entity-texture-features v3.1.1-mc1.19, fabricskyboxes v0.5.6+1.19, freecam v1.0.7+1.19, IKnowWhatImDoing v4.0.0-fabric, indium v1.0.4+mc1.19, iris vmc1.19-1.2.5, lazydfu v0.1.3, lithium-fabric v0.8.0-mc1.19, logical_zoom v0.0.15, notenoughanimations-fabric v1.6.0-mc1.19, optigui v1.1.0, reeses_sodium_options v1.4.3+mc1.19-build.43, sodium-extra v0.4.5+mc1.19-build.43, sodium-fabric v0.4.2-mc1.19+build.16, starlight v1.1.0+fabric.eb9df34, statuseffecttimer v1.1.1+1.19
 - Version [2.1.2]
 - Branch [mc1.19]

**Comment by LambdAurora** [comment]
I need a crash report.
