### ISSUE TITLE
The light emitted by the torch I'm holding is bugged and lags

### ISSUE THREAD

**Issue by luciobortoletto** [LambdAurora/LambDynamicLights#112]
**Describe the bug**
The light emitted by the torch I'm holding is bugged and lags.

**To Reproduce**
1. Open [This modpack](https://modrinth.com/modpack/enmcv/version/1.1.2) (I don't want to advertise it, but I can't reproduce the bug with this mod alone)
2. Enter a world
3. Run command /time set midnight
4. Hold a torch
5. See bug.

**Expected behavior**
I expected the torch not to emit buggy light.

**Screenshots**
Video: https://imgur.com/a/Th0vRxB

**Desktop:**
 - OS: Windows 11
 - Minecraft 1.19
 - Quilt Loader version 0.17.1-beta.6
 - Mods: ![image](https://user-images.githubusercontent.com/52795018/180060315-9f58b8b3-ef52-482d-b75d-1eb7f3933ec7.png)
 - Version 2.1.2
 - From Modrinth

**Additional context**
Sorry if I made some grammar errors, I'm not English

**Comment by LambdAurora** [comment]
This is a side effect of chunk rebuilding.

I'm not sure I can do anything in a reasonable, compatible manner.

**Comment by luciobortoletto** [comment]
But without other mods it doesn't happen... Could you tell me which mod should I remove?

**Comment by luciobortoletto** [comment]
I found out it's Sodium's fault (https://github.com/CaffeineMC/sodium-fabric/issues/1044 - https://github.com/CaffeineMC/sodium-fabric/issues/1035).
