### ISSUE TITLE
Minecraft crashes on mod initializing

### ISSUE THREAD

**Issue by Jacob1Tm** [LambdAurora/LambDynamicLights#114]
**Describe the bug**
Game just crashes when initializing LambDynamicLights

**Expected behavior**
Game don't crash

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.19
 - Fabric Loader version 0.14.8
 - Mods fabric-api v0.57.0+1.19, lambdynamiclights v2.1.2+1.19
 - Version 2.1.2
 - Branch mc1.19

**Additional context**
Launcher that I use is MultiMc
Here crash log:
[crash-2022-07-23_21.42.34-client.txt](https://github.com/LambdAurora/LambDynamicLights/files/9174532/crash-2022-07-23_21.42.34-client.txt)

**Comment by LambdAurora** [comment]
Reset your config file, it got corrupted.

**Comment by Jacob1Tm** [comment]
oh... thanks
