### ISSUE TITLE
Beacon beam & Guardian laser support

### ISSUE THREAD

**Issue by Felix14-v2** [LambdAurora/LambDynamicLights#115]
**Description**
Currently, the beacon beam and the guardian laser are not on the list of dynamic light sources:
![Снимок экрана (4)](https://user-images.githubusercontent.com/75726196/182873739-2ca07ec2-b885-4198-8f07-cb6ae3c7fb4c.png)

It would be great to have the ability to see the light from them, something like this
![Снимок экрана (5)](https://user-images.githubusercontent.com/75726196/182874146-cf3b9725-8c90-44ca-aa65-3e0f2a92e7ee.png)
![2022-08-04_17 50 08](https://user-images.githubusercontent.com/75726196/182877646-1b51c946-814f-4e9d-9966-f05abb69fe9a.png)

I used blocks of light to get the 2nd illustration, but it isn't good solution for visualizing ambient lazer ambient light. However, beacon beam/end gateway looks good.

**Comment by LambdAurora** [comment]
The beacon beams are not entities and all of this would require heavy rework in addition to make this work as the primitive lighting engine the mod has only supports point-based light sources.

In addition, the guardian laser would be lag hell.

**Comment by Felix14-v2** [comment]
And it has no chance of being implemented, at least as an option?
Feel free to close this issue if so.

**Comment by LambdAurora** [comment]
With some recent work done along with @Akarys42, this feature will be added to LambDynamicLights 4 which is due by the Winter Drop (1.21.4).

This has required a huge engineering work on both the API side and the dynamic lighting engine side. I'm quite happy to see a feature that I once thought impossible to finally make it into the mod.

**Comment by LambdAurora** [comment]
Added in LambDynamicLights v4.0.0!
