### ISSUE TITLE
Frame pacing issue when holding a object/block can emit light

### ISSUE THREAD

**Issue by M4th12** [LambdAurora/LambDynamicLights#117]
**Describe the bug**
When you hold a block/object that emits light, frame pacing degrades

**To Reproduce**
1. Pick up any object can emit light
2. Start moving 

**Expected behavior**
You start to feel that the game is not running as smooth as you think. Even if you have 500+ FPS

**Screenshots**
(https://drive.google.com/file/d/1ioePfcF_UpYNgztMX-HeXanYitUlsmkW/view?usp=sharing)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Minecraft: 1.19.2
 - Fabric Loader version: 0.14.9
 - Mods: Continuity 2.0.1 / Emotecraft 2.2.0 build 36 / Fabric API 0.59.0 / Indium 1.0.7 / Iris 1.2.6 / Lithium 0.8.3 / Modmenu 4.0.6 / Mousewheelie 1.10.1 / Phosphor 0.8.1 / Plasmovoice 1.2.19 / Reese Sodium Options 1.4.6 / Sodium extra 0.4.6 / Sodium 0.4.2 / WI Zoom 1.4
 - Version 2.1.2
 - Branch 1.19-1.19.2

**Additional context**

**Comment by SplendidAlakey** [comment]
Try "Always defer chunk updates" option in Sodium settings.

**Comment by coyotepunk05** [comment]
Yep, this seems to fix it.

**Comment by coyotepunk05** [comment]
> Try "Always defer chunk updates" option in Sodium settings.

yep this seems to fix it
