### ISSUE TITLE
Crashes when used with optifabric

### ISSUE THREAD

**Issue by SkylerDust** [LambdAurora/LambDynamicLights#118]
The game crashes when i try to run it as it says that DynamicLights is not compatible with optifabric.
I've tested multiple things and luckily it doesn't have any issues with other mods.

The error that comes up looks like this:

_
> Incompatible mod set!
> net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
> A potential solution has been determined:
> 	 - Replace mod 'LambDynamicLights' (lambdynlights) 2.1.2+1.19 with any version that is compatible with:
> 		 - optifabric 1.13.10
> Unmet dependency listing:
> 	 - Mod 'LambDynamicLights' (lambdynlights) 2.1.2+1.19 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.10!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)_

The game version i am playing is modded java (fabric-0.14.7)

**Comment by LambdAurora** [comment]
I'm gonna have to ask something simple.

Why run this mod and OptiFabric at the same time?

**Comment by SkylerDust** [comment]
bc i simply want all the features, for instance connected glass & optifine zoom are things i hold very dear

**Comment by LambdAurora** [comment]
For connected glass you might want to look into [Continuity](https://modrinth.com/mod/continuity) and for zoom I'm sure [some of the zoom mods there can replicate OptiFine zoom](https://lambdaurora.dev/optifine_alternatives/#zoom).

I do not intend to support OptiFine with this mod as it's opening the door to a lot of potential issues that cannot be easily debugged.
