### ISSUE TITLE
[1.18.2] configs don't save and cause a CME

### ISSUE THREAD

**Issue by DioEgizio** [LambdAurora/LambDynamicLights#119]
**Describe the bug**
On 1.18.2, configs don't save and cause a CME
**To Reproduce**
1. Try to save the config from the GUI
2. See a cme in logs and the changes lost with a game reboot

**Expected behavior**
It working lol

**Desktop (please complete the following information):**
 - OS: macOS
 - Minecraft 1.18.2
 - Fabric Loader version: any 
 - Mods: only LDL and qfapi
 - Version: 2.1.0+1.17

**Additional context**

https://mclo.gs/WNnfcaN

**Comment by Readf0x** [comment]
Not sure what cme is, but this issue also occurs on linux in the latest version

**Comment by LambdAurora** [comment]
I'm not maintaining this version of Minecraft.
