### ISSUE TITLE
Uncompatible with NiceMod blocks

### ISSUE THREAD

**Issue by Psychodeus** [LambdAurora/LambDynamicLights#124]
## **Describe the bug**
[NiceMod](https://modrinth.com/mod/nicemod) blocks look like it only shine to 1 block, overall it appears like it got a tan line.

## **Expected behavior**
Shine all the way to the adjacent block.

## **Screenshots**
![2022-10-16_01 39 37](https://user-images.githubusercontent.com/93028949/196000658-9e2f46cb-803d-4de7-b1f1-07fbe36e5aa9.png)

 ## Spec
- OS: Winodws 10
 - Minecraft 1.19.2
 - Fabric Loader version 0.14.9
 - LambDyanmicLights version 2.1.2

**Comment by LambdAurora** [comment]
I... do not see it?

Please disable your shader and retry.

**Comment by Psychodeus** [comment]
![2022-10-16_01 59 28](https://user-images.githubusercontent.com/93028949/196001518-d6131cdf-e997-452b-9db9-505bcbc9e54e.png)
![2022-10-16_01 39 37](https://user-images.githubusercontent.com/93028949/196001520-09d0ad73-b042-4ae8-a6c9-7a266450c497.png)

They are the same spruce wood btw.

**Comment by LambdAurora** [comment]
This is not an issue with this mod but an issue related to shaders.
