### ISSUE TITLE
Configs don't respect custom game directory [BUG]

### ISSUE THREAD

**Issue by DevScyu** [LambdAurora/LambDynamicLights#126]
### Describe the bug
**Expected:**
Config files to be saved into my custom game directory.
**Actual:**
Config files were saved to the `.minecraft` folder

### To Reproduce
Launch game with different game directory set in the launcher

My profile is set to `%APPDATA%/.wynntils`, however, configs are being saved to `%APPDATA%/.minecraft`
![image](https://user-images.githubusercontent.com/15234414/200563288-a07f6b49-d4e7-4677-818e-fea629b9887c.png)
![image](https://user-images.githubusercontent.com/15234414/200559259-33a3c5a6-7171-49e4-8c23-e1bff7fbcbbd.png)

### Version Information
 - OS: Tested on Mac and Windows
 - Launcher: Official Minecraft Launcher
 - Minecraft 1.18.2
 - Fabric Loader version 0.14.9
 - Mod Version 2.1.0

**Comment by LambdAurora** [comment]
https://bugs.mojang.com/browse/MCL-22685
