### ISSUE TITLE
Fixed position only. I want to disable torch on my hand.

### ISSUE THREAD

**Issue by Psychodeus** [LambdAurora/LambDynamicLights#127]
Is there is a way to disable light (torch) that I carry on my hand to emit lights?
I just want to use this mod as a fixed position source block like glow item frame, lantern, etc. But not when I walk.
How to disable it?

**Comment by onkoe** [comment]
seems like `lambdynlights.tooltip.mode.1` in your config will handle this!

**Comment by LambdAurora** [comment]
The latest release should introduce the setting you want.
