### ISSUE TITLE
LambDynamicLights is not supported on 1.19.3.

### ISSUE THREAD

**Issue by Kichura** [LambdAurora/LambDynamicLights#130]
**Describe the bug**
LambDynamicLights has issues running properly in 1.19.3 due to the fact that the "field_11142" field is absent entirely unlike 1.19 and 1.19.1/2, But this also includes it causing boot loops when trying to load the mod with it.

**To Reproduce**
1. Get the latest LambDynamicLights copy, *(v2.1.2 at this time)*
2. Add this mod to a 1.19.3 instance with a compatible version of the Fabric API mod,
3. Start the modified client and expect it to boot-loop.

**Expected behavior**
LambDynamicLights continues to run as intended without major issues.

**Screenshots**
*(Unable to provide any in this section)*

**Desktop (please complete the following information):**
 - OS: Linux
 - Minecraft: 1.19.3
 - Fabric Loader version: 0.14.11
 - Mods: LambDynamicLights *(2.1.2+1.19)*, Fabric API *(0.68.1+1.19.3)* and LazyDFU *(0.1.3)*
 - Branch: 1.19

**Additional context**
I cannot be sure if this mod is still maintained at all or if anything else is planned for it in the first place but i rather wanna push out this issue in case any duplicates appear.

**Comment by LambdAurora** [comment]
LambDynamicLights has not 1.19.3 marked as supported on mod hosting websites.

**Comment by Kichura** [comment]
Expected.

Although the `>=1.19` context in the fabric.mod.json file can actually make some people assume that the mod itself supports any minor version of 1.19 in general when it's not quite true.

**Comment by LambdAurora** [comment]
It was supposed to be true but Mojang wrecked the assumption for good and I don't want to upload a new release only to make the version restrictions tighter.

**Comment by litoj** [comment]
Is there a way to fix the boot loop?

**Comment by moehreag** [comment]
> Is there a way to fix the boot loop?

remove the mod for now and wait until our lovely foxolotl has regained a good enough mental state to efficiently work on mods again

**Comment by LagPixelLOL** [comment]
i fixed the issue and made a pull request, if you guys want to use updated version but dont want to wait until merge, you can go to my fork and download from action!

**Comment by laforcem** [comment]
Thanks @LagPixelLOL, your fork works perfect for me in the meantime!

**Comment by venaminecraft** [comment]
Thank you @LagPixelLOL.

**Comment by BBloom81** [comment]
> It was supposed to be true but Mojang wrecked the assumption for good and I don't want to upload a new release only to make the version restrictions tighter.

Can you explain at all?  I'm genuinely curious what they did to this revision that's so different for mods vs 1.19.1 and .2

Thank you

**Comment by LagPixelLOL** [comment]
> > It was supposed to be true but Mojang wrecked the assumption for good and I don't want to upload a new release only to make the version restrictions tighter.
> 
> Can you explain at all? I'm genuinely curious what they did to this revision that's so different for mods vs 1.19.1 and .2
> 
> Thank you

They moved "net.minecraft.**util**.registry.Registry" to "net.minecraft.registry.Registry", also they moved the registry keys and registry enumerations to separate classes and i think its a good thing, because they were in the same class before and its kinda confusing.

**Comment by LambdAurora** [comment]
That's not really the only reason.

I guess people don't really pay attention to what Mojang says.
They basically announced they will wreck any meaning that snapshots had, and will allow "snapshot content" from the next major release to be added in minor releases behind datapacks. Except that doesn't mean just new JSONs, this means new code **and refactors**.
They basically just announced that breakage will be a common occurrence between minor versions.

**Comment by LagPixelLOL** [comment]
> That's not really the only reason.
> 
> I guess people don't really pay attention to what Mojang says. They basically announced they will wreck any meaning that snapshots had, and will allow "snapshot content" from the next major release to be added in minor releases behind datapacks. Except that doesn't mean just new JSONs, this means new code **and refactors**. They basically just announced that breakage will be a common occurrence between minor versions.

Thanks for the information!
But i think the refactors are actually not that bad and they made the codebase more clean.

**Comment by LambdAurora** [comment]
Refactors are useful, my only issue here is they said it will happen every few months instead of every big release.
Which, for mod authors, especially with little time (or even worse burn out), is terrible!

**Comment by LagPixelLOL** [comment]
I think bukkit did a better job at this, if mods interact with api instead of using mixins directly, we can avoid incompatible issues.

**Comment by LambdAurora** [comment]
Bukkit did not.

Its over-obsessiveness over not breaking anything led to API designs that don't make any sense in modern versions and are just a pain to work with.
There's a good reasons that any modern attempts to merge Bukkit and modded leads to garbage fire.

**Comment by LambdAurora** [comment]
Thank you @LagPixelLOL for your work.
I just had to update pridelib to avoid one last issue and that was it!
The update is on its way to your favorite mod provider.
