### ISSUE TITLE
Majority of the functions don't work on 1.19.3

### ISSUE THREAD

**Issue by Stelicx** [LambdAurora/LambDynamicLights#136]
**Describe the bug**
Creepers, TNTs do not emit any light, even if they are set to Fancy. I tried some other blocks which I remember them emitting light such as brewing stand but they also do not seem to work anymore. Only thing that I can see is working is that the handheld torch and some mobs such as glow squid, allay. I removed all my mods and used this mod with only Fabric API and Mod Menu, so there is nothing that causes issue.

**To Reproduce**
As explained above, just put some TNT and Creepers while they are set to work on Fancy mode or any other mode, you'll see that they dont emitate any light, along with many other blocks.

**Expected behavior**
I expected them to have some emissive light, which I saw happening in versions 1.19 - 1.19.2

**Screenshots**
https://prnt.sc/BywtSXxbAgnj

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.19.3
 - Fabric Loader version 0.14.13-1.19.3
 - Mods [e.g. fabric-api v0.73.0, lambdynamiclights v2.2.0, modmenu v5.0.2, Fabric Language Kotlin 1.9.0+kotlin1.8.0]
 - Version ????
 - Branch ??? what

**Additional context**
No additional stuff.

**Comment by LambdAurora** [comment]
TNT and Creepers are separate settings and they only emit light when they're about to explode.

As for the mention of brewing stand I have no idea what you're talking about, I've never touched the light emission of brewing stand.

**Comment by Stelicx** [comment]
"they only emit light when they're about to explode", oh do they??? I thought this mod gave them passive emission which was active all the time. I guess it must be another mod that did that and also affected the brewing stand stuff. Sorry for the trouble.
