### ISSUE TITLE
Enchancment: Add a brightness modifier slider/multiplier

### ISSUE THREAD

**Issue by MageInBlack** [LambdAurora/LambDynamicLights#137]
**Is your feature request related to a problem? Please describe.**
I wanted to make this mod go alongside my shaders and probably even remove handheld light as shaders do not implement it very well. And I wanted to put it in my hard modpack as well but i can't get the brightness of items quite right as default values either too small or too big

**Describe the solution you'd like**
It would be nice if this mod had a brightness modifier slider. At least a global one. So brightness of items can be configured, maybe make a limit of 15 or what was the default max value

**Comment by LambdAurora** [comment]
I strictly work within the limits of what the Vanilla game gives me.
