### ISSUE TITLE
I have heard you are moving to quilt

### ISSUE THREAD

**Issue by Danjhop4** [LambdAurora/LambDynamicLights#138]
Is it true

**Comment by LambdAurora** [comment]
Not really.

This specific mod is staying on Fabric *for now*.
If Quilt has a technical advantage that this mod can directly use then it'll probably switch, or if maintenance becomes too much of a burden on Fabric.

tl;dr no plans for now

I'm wondering where you've heard that? or are you just confusing this mod with LambdaBetterGrass?
