### ISSUE TITLE
Remove extra lib mod

### ISSUE THREAD

**Issue by tennomai** [LambdAurora/LambDynamicLights#139]
**Is your feature request related to a problem? Please describe.**
Don't want politics in video games

**Describe the solution you'd like**
Option to remove pride lib

**Describe alternatives you've considered**
not using the mod or I might try prying into the jar archive

**Additional context**
no context

**Comment by LambdAurora** [comment]
Depends on how you see it, should the existence of some people who don't hurt anyone be political?

Also not wanting politics in video games is so naive. Art is political, it always has been. Here's some resources and examples:
 - [The arts and politics - Wikipedia](https://en.wikipedia.org/wiki/The_arts_and_politics)
 - [All Art Is Political](https://www.outervoice.net/home/political)
 - Several video games are literally a critic of the world
   - Ratchet & Clank (2002) is literally a critic of capitalism (isn't that political?)
   - The Fallout games are inherently political even if they base themselves into a fictional setting
   - Disco Elysium
   - Hardspace Shipbreaker which approaches the topic of capitalism and unions
   - Bioshock, the series is notable for exploring philosophical and moral concepts with a strong in-game narrative influenced by concepts such as [Objectivism](https://en.wikipedia.org/wiki/Objectivism), [total utilitarianism](https://en.wikipedia.org/wiki/Total_utilitarianism), and [American exceptionalism](https://en.wikipedia.org/wiki/American_exceptionalism).
   - Death Stranding (plot can be compared to the COVID-19 pandemic)
   - The Metal Gear series
 - [Minecraft Game Art Director expressing support towards the LGBTQ+ community](https://nitter.pussthecat.org/JasperBoerstra/status/1400824812554096642#m)
   
So please grow up :)
   
Also, you're getting hurt by colors...

**Comment by tennomai** [comment]
No need to get so defensive, I mentioned nothing about being hurt or offended.
In fact, I have a couple of suggestions:
Since you love supporting the rights of people who are being hurt and abused, why not extend it to countries as well?

There is a veery long list of people being oppressed every single day, some of which:
Syria
Lebanon
Afghanistan
Palestine
Alot of African countries
Ukraine
Swedish muslims
Algeria
And the list continues.
Where is the option of having these flags instead? Where is the support for human rights?

If you truly were a liberal who really DOES support human rights, freedom, and equality, shouldn't these flags be in the mod? Doesn't liberalism tolerate every single belief and freedom of thinking and freedom of speech? 

Notice how most of those games aren't supposed to be played by kids?

Minecraft is a game to relax in, to free yourself from the dilemmas of the world, not a game to share your agenda with.

Also, how does a sensible person come to the conclusion that the removal of flags indicates the removal of such people from the world?? Does your existence depend on the pride flags? If I burned a pride flag would lgb people start dying on the spot? Pretty ridiculous if you ask me.

Anyways, this is not worth my time, I'll probably just pry into the jar file in my free time and see if I can replace those flags with the flags of the people who were demolished and destroyed by the liberal powers.

**Comment by TwilightFlower** [comment]
You don't want politics in your game, and yet you'd willingly put in country flags? Something tells me you don't actually care about politics, but instead are just queerphobic.

**Comment by tennomai** [comment]
That's really just a strawman lol. You implied that you put pride flags to support lgb people, so I found that since there is no hope of asking you to add an option to remove them, I realized I should just use your own liberalism and human rights tactics against you. Good luck escaping this one chief.
