### ISSUE TITLE
[1.2.3] NPE on launch

### ISSUE THREAD

**Issue by Leo40Git** [LambdAurora/LambDynamicLights#14]
<https://paste.ee/p/0TPhE>
Using 1.2.3 (https://github.com/LambdAurora/LambDynamicLights/commit/2c79dcd879dd415fedc2e7f6db762dd3fdd27296).
This only happens when LambDynamicLights is enabled. Without it, it launches fine.

**Comment by Leo40Git** [comment]
I... didn't build it correctly (`build` instead of `shadowRemapJar`).
Damn your non-standard build instructions /s

**Comment by LambdAurora** [comment]
Well, the non-standard build instruction is to avoid libraries shadowing on Maven builds. I just wanted to avoid to pollute the Maven  jar but the result is it's very confusing.
