### ISSUE TITLE
Update the mod to 1.19.4

### ISSUE THREAD

**Issue by TechPro424** [LambdAurora/LambDynamicLights#141]
**Is your feature request related to a problem? Please describe.**
The mod is incompatible with 1.19.4

**Describe the solution you'd like**
Please update the mod to 1.19.4

**Comment by Secret-chest** [comment]
And please no quilt-only

**Comment by LambdAurora** [comment]
I wasn't planning on switching to Quit as this mod doesn't need a Quilt-only API yet.

But reminder that you are not entitled to choose the mod loader of a mod. And out of all the options, Quilt isn't the worst loader to switch to.

**Comment by greggh** [comment]
Definitely waiting on this one for 1.19.4. Thanks for the awesome mod.

**Comment by Poopooracoocoo** [comment]
Please do not write 'me too' comments. GitHub introduced reactions for that exact reason as it clutters peoples inboxes.

**Comment by falcie1337** [comment]
i definitely want this on 1.19.4, such a pain to play on fabric and not be able to use torch hand light while mining, this mod is a banger

**Comment by Drunknbyte** [comment]
Anyone can share a PR or beta version to try?  thnks in advance.
