### ISSUE TITLE
Dynamic lighting very laggy on Better MC 1.19.2 v16.5

### ISSUE THREAD

**Issue by Zakifiruz** [LambdAurora/LambDynamicLights#146]
Never have issues with fancy dynamic lighting on optifine, but am having huge lag when carrying light emitting object with this mod. Any fixes?

**Comment by Elfrrik** [comment]
I've found that enabling a certain Sodium option helps.
Navigate to your config folder and open the sodium-options Json file.
Change **"always_defer_chunk_updates"** to **true**.

You may also set **Particles** to **decreased** in-game which can potentially help reduce lag. Hope it helps!

**Comment by LambdAurora** [comment]
As said previous, enabled chunk updates deferring helps a lot!
