### ISSUE TITLE
Block entities do not show names in settings

### ISSUE THREAD

**Issue by Madis0** [LambdAurora/LambDynamicLights#147]
**Describe the bug**
Block entities do not show their names in settings, while entities do.

**To Reproduce**
1. Get LDL and Mod Menu
2. Open LDL config
3. See "Entities" section
4. See "Block Entities" section

**Expected behavior**
Expected localized names

**Screenshots**
![Screenshot_20230329_222931](https://user-images.githubusercontent.com/8611110/228647409-6545d79d-003d-4190-930c-a81629a1b291.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Minecraft 1.19.4
 - Fabric Loader version 0.14.18
 - Mods 
![Screenshot_20230329_223146](https://user-images.githubusercontent.com/8611110/228647808-7f58d06a-2ace-47c4-ab9d-5da0801fb5af.png)

 - Version 2.3.0+1.19.4
 - Branch N/A

**Additional context**
N/A

**Comment by LambdAurora** [comment]
Block entities do not have localized names.

**Comment by Madis0** [comment]
How come? Every block in that list has a localized string in the format `block.minecraft.name`, e.g. `block.minecraft.furnace`.

Edit: okay, maybe not _all_ of them, e.g. hanging sign does not have a generic string and `mob_spawner` is instead `spawner`.

**Comment by LambdAurora** [comment]
Block != Block Entity
