### ISSUE TITLE
LambDynamicLights broken on macOS using Minecraft 1.19.4

### ISSUE THREAD

**Issue by aellul27** [LambdAurora/LambDynamicLights#151]
**Describe the bug**
LambDynamicLights crashes when opening it in modmenu or **opening a world** macOS on the 1.19.4 build.

**To Reproduce**
1. Install forge and lambdynamiclights
3. Run installation
4. Open any world
5. See error

**Expected behavior**
The expected behavior is that the world renders in allowing the player to play in that server instance. Instead, lambdynamic lights crashes.

**Desktop (please complete the following information):**
 - OS: macOS 12.6.5 
 - Minecraft 1.16.4
 - Fabric Loader version 0.14.9
 - Mods fabric-api-0.78.0+1.19.4, iris-mc1.19.4-1.6.1, lithium-fabric-mc1.19.4-0.11.1, phosphor-fabric-mc1.19.x-0.8.1, sodium-fabric-mc1.19.4-0.4.10+build.24, modmenu-6.2.1, lambdynamiclights-2.3.0+1.19.4
 - LambDynLights Version 2.3.0
 - Branch 1.19.4

**Additional context**
The error that seems to be causing it is:
[23/04/2023 18:15:29 pm] Caused by: java.nio.file.NoSuchFileException: config/lambdynlights.toml
[23/04/2023 18:15:29 pm] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[23/04/2023 18:15:29 pm] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[23/04/2023 18:15:29 pm] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)

[1.19.4 Log](https://github.com/LambdAurora/LambDynamicLights/files/11303208/latest.log)

**Comment by Fnige** [comment]
> Caused by: java.nio.file.NoSuchFileException: config/lambdynlights.toml

If you have a ldl config in your config folder, try deleting it

**Comment by aellul27** [comment]
FnigePython no effect by deleting config/lambdynlights.toml

**Comment by CuddlyZombie** [comment]
+1, I'm having the exact same issue, my exception is instead 

`dev.lambdaurora.lambdynlights.shadow.nightconfig.core.io.WritingException: Error while saving the FileConfig to config/lambdynlights.toml
`
Deleting the file did not resolve it.

**Comment by phiberber** [comment]
I'm actually having both errors:

```ts
[07/05/2023 15:38:37 PM] dev.lambdaurora.lambdynlights.shadow.nightconfig.core.io.WritingException: Error while saving the FileConfig to config/lambdynlights.toml
[07/05/2023 15:38:37 PM] 	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.file.WriteAsyncFileConfig$WriteCompletedHandler.failed(WriteAsyncFileConfig.java:166)
```

And

```ts
[07/05/2023 15:38:37 PM] Caused by: java.nio.file.NoSuchFileException: config/lambdynlights.toml
```

I would assume that the path is wrong? Lambdynlights.toml does exist in the config folder, Java would not prompt a NoSuchFileException with an existing file, and I would doubt the mod is deleting the config file at anytime.

After learning a little about Fabric and how other mods make config implementations, I'm inclined to say that the problem is in the line 
https://github.com/LambdAurora/LambDynamicLights/blob/a2da510bda2bf17ca638eb900f648116319635d8/src/main/java/dev/lambdaurora/lambdynlights/DynamicLightsConfig.java#L41

Having by example [BorderlessMining](https://github.com/comp500/BorderlessMining/blob/db51ed158a489f415ab137b24353adc0fd11f4d0/src/main/java/link/infra/borderlessmining/config/ConfigHandler.java#L18) 

```java
	import net.fabricmc.loader.api.FabricLoader;

        [...]
	private static final transient Path configFile = FabricLoader.getInstance().getConfigDir().resolve("borderlessmining.json");
```

**Comment by aellul27** [comment]
Opened a pull request to fix this issue: #152

**Comment by aellul27** [comment]
Opened a pull request to fix this issue: #152

**Comment by phiberber** [comment]
What's the reason behind the re-opening? Did the issue persist?

**Comment by aellul27** [comment]
Pull request #152 has not been applied to the repositiory. I have re-opened the issue so people who are encountering the issue can find the required changes and to bring attention to the issue.

**Comment by aellul27** [comment]
> What's the reason behind the re-opening? Did the issue persist?

Pull request #152 has not been merged with the repositiory. I have re-opened the issue so people who are encountering the issue can find the required changes and to bring attention to the issue.
