### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by oZxrvon** [LambdAurora/LambDynamicLights#153]
**Describe the bug**
Game crash while its starting
**To Reproduce**
1. Use it in my minecraft pack
2. launch
3. see error

**Expected behavior**
it just crashed during the loading process
**Screenshots**

**Desktop (please complete the following information):**
 - OS: HP Pavillion
 - Minecraft 1.17.1
 - Fabric Loader version 0.14.19
 - Mods not sure if you want every mod im using or just the dynamic lights one
 - Version 2.1.0+1.17
 - Branch idk what this means lol
**Additional context**
it gave me this link, idk if itll help lol
https://bytebin.lucko.me/VLHtiJdYSs
also i have used the exact same modpack before and it worked so i dunno whats wrong

**Comment by Leon135** [comment]
Propabbly mod conflict.  You could attach log from the crash

**Comment by LambdAurora** [comment]
1.17 is unsupported.

And there's no valid context attached.
