### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by LukaTV939** [LambdAurora/LambDynamicLights#154]
As the title says new version came out and old mods that are not updated don't work

**Comment by lospejos** [comment]
@LukaTV939 Why you tagged this issue as a bug? IMHO this is rather the feature or improvement.

**Comment by LukaTV939** [comment]
> @LukaTV939 Why you tagged this issue as a bug? IMHO this is rather the feature or improvement.

My bad, I was in a hurry and didn't think about it. Can I change the tag somehow?

**Comment by lospejos** [comment]
> My bad, I was in a hurry and didn't think about it. Can I change the tag somehow?

Maybe just edit your issue. I cannot edit this since I'm not this issue's author.

**Comment by mk-pmb** [comment]
In case someone needs a JAR download for 1.20, [here's my build](https://github.com/mk-pmb/ghabuild-simple-gradle-projects/releases/tag/rolling/gh/lambdaurora/lambdynamiclights) of PR #156. @Lisixo, thanks a lot for providing!

> Maybe just edit your issue.

I just tested with one of my own issue threads in another repo. Seems like by default, regular users cannot edit their thread's tags.

**Comment by LukaTV939** [comment]
> In case someone needs a JAR download for 1.20, [here's my build](https://github.com/mk-pmb/ghabuild-simple-gradle-projects/releases/tag/rolling/gh/lambdaurora/lambdynamiclights) of PR #156. @Lisixo, thanks a lot for providing!
> 
> > Maybe just edit your issue.
> 
> I just tested with one of my own issue threads in another repo. Seems like by default, regular users cannot edit their thread's tags.

The release is empty :/

**Comment by mk-pmb** [comment]
@LukaTV939 That's odd. Maybe Github had a temporary failure? Anyway you can easily build your own, just open a repo on GitHub, import the files from [my build branch](https://github.com/mk-pmb/ghabuild-simple-gradle-projects/tree/build-gh/lambdaurora/lambdynamiclights), and push it to GitHub. Even if you don't set a publish token, you can still access the build artifact from your own GitHub Actions run. The artifact should work the same just the filename is wrong.

**Comment by LukaTV939** [comment]
> @LukaTV939 That's odd. Maybe Github had a temporary failure? Anyway you can easily build your own, just open a repo on GitHub, import the files from [my build branch](https://github.com/mk-pmb/ghabuild-simple-gradle-projects/tree/build-gh/lambdaurora/lambdynamiclights), and push it to GitHub. Even if you don't set a publish token, you can still access the build artifact from your own GitHub Actions run. The artifact should work the same just the filename is wrong.

Thanks, I can see there releases so it's even better

**Comment by NatoBoram** [comment]
Thanks @LambdAurora 💙

**Comment by LukaTV939** [comment]
> Thanks for raising attention towards the need for a port to a Minecraft version.
> 
> Though, the author is already aware of such version, there isn't much need for further comments.  
> Given an annoying increase in "new version when" comments on diverse platforms, such issues won't allow comment anymore
> as it does not help making a faster release.
> 
> Thank you for your understanding.

I made an issue cuz the update was then like 2 months ago, plus it's only a issue and just wanted to get notified when it's closed and updated

**Comment by LambdAurora** [comment]
It was not that far lmao.

This system is mostly for future issues, here it only lasted a few hours as a test.
