### ISSUE TITLE
Crash (1.19.4)

### ISSUE THREAD

**Issue by Wispots** [LambdAurora/LambDynamicLights#155]
**Describe the bug**
When i try to manage LambDynamicLights settings through ModMenù the game crashes.

**To Reproduce**
1. Start Minecraft with the Fabric-loader-0.14.19-1.19.4, including the mods you can see in the crash report in the mods folder.
2. Click "Mods"
3. Go to LambDynamicLights 
4. Click the settings button on the top right
5. crash

**Expected behavior**
I expected the menù of the mod opening up

**Desktop:**
 - OS: Windows 11
 - Minecraft 1.19.4
 - fabric-loader-0.14.19-1.19.4
 - Mods:  lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		litematica: Litematica 0.14.3
		malilib: MaLiLib 0.15.3
		minecraft: Minecraft 1.19.4
		minihud: MiniHUD 0.26.2
		modmenu: Mod Menu 6.2.3
		sodium: Sodium 0.4.10+build.24
		tweakeroo: Tweakeroo 0.16.0
		xaerominimap: Xaero's Minimap 23.4.0
 - Branch: i dunno what this is

**Additional context**
Others mods' menus (through ModMenu)
[crash.txt](https://github.com/LambdAurora/LambDynamicLights/files/11710117/crash.txt)

**Comment by LambdAurora** [comment]
You are using an outdated version of LambDynamicLights.
