### ISSUE TITLE
Support Minecraft 1.20 Version plz

### ISSUE THREAD

**Issue by AkarinLiu** [LambdAurora/LambDynamicLights#157]
**Is your feature request related to a problem? Please describe.**
Yes, I am Modrinth Modpacks Creator, I need Latest Minecraft Version Mods.

**Describe the solution you'd like**
Minecraft Is Release 1.20 Version

**Describe alternatives you've considered**
Optifine & OptiFabric

**Additional context**
I am Modpacks Creator, I hope this Mod can be support Minecraft 1.20.
[My Modrinth](https://modrinth.com/user/AkarinLiu)

**Comment by LambdAurora** [comment]
Come on, there's already another issue about it... And that other issue already frustrated me.

Like, I know some of y'all want to do good, but that's just an incredible source of frustration, I already had to delete 3 comments asking for ports on the CF page.
