### ISSUE TITLE
Not compatible with 1.20

### ISSUE THREAD

**Issue by rakantoh** [LambdAurora/LambDynamicLights#160]
The version 2.3.1 of lambdynamic lights doesn´t works in minecraft fabric 1.20, shows a message that requires fabric api 0.83.1 1.20.1, but fabric api 0.83.1 is ONLY compatible with 1.20.1, for 1.20 only exists fabric api 0.83.0.
Simply, the game crashes with both fabric api versions (0.83.0 or 0.83.1)

Windows 10 Pro x64
Minecraft 1.20
Fabric Loader 0.14.21
Fabric api 0.83.x Lambdynamiclights 2.3.1
![imagen_2023-06-21_155220922](https://github.com/LambdAurora/LambDynamicLights/assets/59809634/123d1217-aec1-4bf2-80b5-42d214d54abd)

**Comment by LambdAurora** [comment]
Update to Minecraft 1.20.1.
It is a very small release for which most mods should be compatible with out of the gate or have most likely already an update available.

**Comment by rakantoh** [comment]
> Update to Minecraft 1.20.1. It is a very small release for which most mods should be compatible with out of the gate or have most likely already an update available.

in my case at least 8 mods still no 1.20.1 update, so i must stay for now in 1.20

**Comment by giuliotoplad** [comment]
> The version 2.3.1 of lambdynamic lights doesn´t works in minecraft fabric 1.20, shows a message that requires fabric api 0.83.1 1.20.1, but fabric api 0.83.1 is ONLY compatible with 1.20.1, for 1.20 only exists fabric api 0.83.0. Simply, the game crashes with both fabric api versions (0.83.0 or 0.83.1)
> 
> Windows 10 Pro x64 Minecraft 1.20 Fabric Loader 0.14.21 Fabric api 0.83.x Lambdynamiclights 2.3.1 ![imagen_2023-06-21_155220922](https://user-images.githubusercontent.com/59809634/247755829-123d1217-aec1-4bf2-80b5-42d214d54abd.png)

This is my solution:
You have to install the latest Fabric API version that is Beta 0.84.0+1.20.1 and everything should work fine.
You can find it from here: https://modrinth.com/mod/fabric-api/versions

**Comment by rakantoh** [comment]
Again... fabric api 0.83.1 and 0.84.0 it's ONLY for Minecraft 1.20.1 not 1.20... 
fabric api 0.83.1 and 0.84.0 no works on 1.20....
it's clear?

**Comment by giuliotoplad** [comment]
> Again... fabric api 0.83.1 and 0.84.0 it's ONLY for Minecraft 1.20.1 not 1.20... fabric api 0.83.1 and 0.84.0 no works on 1.20.... it's clear? 

Yes it's clear, sorry about that.
However I use it on Minecraft 1.20 and it works, I only want to say this, that's it.
I only offered a temporary solution, nothing more.

**Comment by rakantoh** [comment]
> > Again... fabric api 0.83.1 and 0.84.0 it's ONLY for Minecraft 1.20.1 not 1.20... fabric api 0.83.1 and 0.84.0 no works on 1.20.... it's clear?
> 
> Yes it's clear, sorry about that. However I use it on Minecraft 1.20 and it works, I only want to say this, that's it. I only offered a temporary solution, nothing more.

ok, then i will try, but in my first tests always crashes, i will try again

**Comment by giuliotoplad** [comment]
> > > Again... fabric api 0.83.1 and 0.84.0 it's ONLY for Minecraft 1.20.1 not 1.20... fabric api 0.83.1 and 0.84.0 no works on 1.20.... it's clear?
> > 
> > 
> > Yes it's clear, sorry about that. However I use it on Minecraft 1.20 and it works, I only want to say this, that's it. I only offered a temporary solution, nothing more.
> 
> ok, then i will try, but in my first tests always crashes, i will try again

Ok, then you can close this issue.
Fabric Mods are already almost all updated (the most important) to Minecraft 1.20.1.
I think [LambdAurora](https://github.com/LambdAurora) will skip 1.20 so you should do that too.

**Comment by rakantoh** [comment]
in my case 4 mods have no update to 1.20.1, only 1.20, so im going to keep on 1.20 for now, and i will no more use lambdynamiclights, at least for now, any ways thanks.

**Comment by Mouy07** [comment]
Using Better Statistics Screen 2.10.3 allows LambDynamicLights 2.3.1 to run on Minecraft 1.20 with Fabric API 0.83.0. I have no idea why.
