### ISSUE TITLE
Crash on Start up

### ISSUE THREAD

**Issue by AlfmanOO7** [LambdAurora/LambDynamicLights#161]
**Describe the bug**
When starting Minecraft the game will crash causing an exit code (-1) and this error message:

> The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'lambdynlights'!

**To Reproduce**
Steps to reproduce the behaviour:
1. Open launcher
2. Press 'play'
3. wait
4. crash occurs

**Expected behaviour**
That the game would load

**Screenshots**
![image](https://github.com/LambdAurora/LambDynamicLights/assets/62825044/833f0b04-5312-4fa3-8542-50742e4e5445)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Minecraft 1.19.4
 - Fabric Loader version Quilt 0.19.0 Beta 18
 - Mods | Version
3D Skin   Layers | 1.5.3
Adaptive Tooltips | 1.2.1
Advancement Plaques | 1.4.9
AdvancementsInfo | 1.3.1
Ambient Sounds | 5.2.19
Animatica | 0.5.0
Appleskin | 2.4.3
Architectury | 8.1.87
Armor Chroma for Fabric | 1.2.5
AuthMe | 6.1.0
Auto Clicker | 1.6.1
Better F3 | 6.0.2
Better Mount HUD | 1.2.1
Better Ping Display | 1.1.1
Blur | 3.0.0
Bobby | 4.0.5
Borderless Mining | 1.1.7
Camera Overhaul | 1.4.0
Camera Utils | 1.0.4
Chat Heads | 0.10.14
Chat Patches | 194.4.6
CITResewn | 1.1.3
Client Side Noteblocks | 2.4.0
Cloth Config | 10.0.96
Colorful Hearts | 3.0.0
Colorful Subtitles | 1.2.0
Colour My Servers | 1.0.4
Complete Config | 2.3.1
Continue (Button) | 1.1.0
Continuity | 3.0.0 Beta 2
CreativeCore | 2.10.12
Dark Loading Screen | 1.6.13
Death Log | 0.3.2
Do a Barrel Roll | 2.8.2
Durability Notifier | 1.5.0
Dynamic App Icon | 0.1.1
Dynamic Crosshair | 6.2.1
Dynamic Sound Filters | 1.4.0
Eating Animation | 1.9.3
EnhancedVisuals | 1.6.3
Entity Model Features | 0.2.9
Entity Texture Features | 4.4.4
Equipemt Compare | 1.3.6
Fabric Carpet | 1.4.101
Fabric Language Kotlin | 1.9.4
Falling Leaves | 1.15.0
FerriteCore | 5.2.0
First Person Model | 2.2.3
Forge Config API Port | 6.0.2
Fuel Info | 1.0.2
Iceberg | 1.1.10
Indium | 1.0.17
Inspecio | 1.8.0
Inventory HUD+ | 3.4.12
Iris (Shaders) | 1.6.4
Item Borders | 1.2.0
Item Scroller | 0.19.2
Item Swapper | 0.4.0
Legendary Tooltips | 1.4.3
Litematica | 0.14.2
Lithium | 0.11.1
Make Bubbles Pop | 0.1.1
MaLiLib | 0.15.4
Mambience | 5.3.0
MemoryLeakFix | 1.0.0
Minihud | 0.26.2
Mixin Trace | 1.1.1
Mod Menu | 6.2.2
NBT Autocomplete | 1.1.2
No Chat Reports | 2.1.4
Not Enough Animations | 1.6.4
OptiGUI | 2.1.0 Beta 3
oωo (owo-lib) | 0.10.6
Physics Mod | 2.12.4b
Presence Footsteps | 1.8.2
Prism | 1.0.4
Quilted Fabric API &   Quilt Standard Libraries | 6.0.0 Beta 9 & 5.0.0 Beta 10
Reese's Sodium Options | 1.5.0
Remote Players | 2.0.2
Replay Mod | 2.6.12
Satin API | 1.12.1
Seamless | 1.3.0
Shulker Pick | 1.0.0
Shulkerbox Tooltip | 3.3.1
Simple Shulker Preview | 2.3.1
SmoothBoot | 1.7.0
SmoothSwapping | 0.9.1
Sodium Extra | 0.4.18
Sodium Fabric | 0.4.10
Spyglass Astronomy | 1.0.5
Starlight | 1.1.1
Stendhal | 1.3.7
Tiny Item Animations | 1.0.0
Travellers Toasts | 1.1.0
Tweakeroo | 0.16.0
Visuality | 0.7.0
Void Fog | 2.9.0
Wavey Capes | 1.4.0
Xaero's Minimap | 23.4.4
Xaero's World Map | 1.30.3
Yet Another Config Lib | 3.0.0 Beta 1
Zoomify | 2.9.4
LambDynamicLights | 2.3.1

 - Branch ???

**Additional context**
See attached crash log and game log
[latest.log](https://github.c
[crash-2023-06-22_09.33.39-client.txt](https://github.com/LambdAurora/LambDynamicLights/files/11826366/crash-2023-06-22_09.33.39-client.txt)
om/LambdAurora/LambDynamicLights/files/11826365/latest.log)

**Comment by LambdAurora** [comment]
Please delete the file in your game instance `config/lambdynamiclights.toml` as the configuration is corrupted.

**Comment by AlfmanOO7** [comment]
This worked! Thank you so much for the quick response. I would have never thought to look into the configs
