### ISSUE TITLE
Invalid Version on Prism Launcher

### ISSUE THREAD

**Issue by giuliotoplad** [LambdAurora/LambDynamicLights#162]
LambDynamicLights v2.3.1 seems not compatible for Minecraft 1.20 if I check for updates that should work normally like all others mods.
I started the client and the mod seems to works fine after installing the required Fabric API beta version.

![image](https://github.com/LambdAurora/LambDynamicLights/assets/36372281/1d8dc269-76e5-45b3-b8da-5374b0fc40bf)

If I'm not wrong when I installed the mod from the Launcher it says like something about meta data or something.

**Comment by LambdAurora** [comment]
Update to Minecraft 1.20.1 as it's a very minor release most mods should work.
