### ISSUE TITLE
LambDynamicLights isnt compatibel with MC ver 1.20.0

### ISSUE THREAD

**Issue by BlueStarBRS** [LambdAurora/LambDynamicLights#165]
**Describe the bug**
is crashes on startup while it will sayed this is supported for 1.20.0

pls make it running on 1.20 there a lot of mods who are not updated to 1.20.1 at least important Performance mods

**Comment by KAGUYA-1137** [comment]
Open "lambdynamiclights-2.3.1+1.20.1.jar" with WinRAR or 7zip and open fabric.mod.json on text editor. 
Change the fabric and minecraft versions in the depends column.

```
    "fabric": "\u003e\u003d0.83.0+1.20",
    "minecraft": ">=1.20",
```

**Comment by Migats** [comment]
The thing is that the code does actually run on 1.20.0. It is just that they wrote their dependencies specificly for 1.20.1

**Comment by Mouy07** [comment]
Using Better Statistics Screen 2.10.3 allows LambDynamicLights 2.3.1 to run on Minecraft 1.20 with Fabric API 0.83.0. I have no idea why.
