### ISSUE TITLE
Carry-only light sources

### ISSUE THREAD

**Issue by ColonelGerdauf** [LambdAurora/LambDynamicLights#166]
**Is your feature request related to a problem? Please describe.**
While there are light sources that one can hand-hold, they can be placed on to blocks, which can create awkwardness when a player isn't super-careful with their buttons.

**Describe the solution you'd like**
An entity light source, like a form of a torch. This torch cannot be placed anywhere that is not a storage block, and the action button can actually switch the light from on to off, if the player builds a torch with such mechanism. So there are at lest 2 carryable light sources, one with and one without the light switch, and it is up to user choice as to which one they want to have.

**Describe alternatives you've considered**
Maybe an attachable light source in a helmet? One that can be turned on/off with a set key.

**Comment by LambdAurora** [comment]
You're asking features that'd best fit a content mod rather than a client mod.
Such content mod could use this mod's API though.
