### ISSUE TITLE
stopped working with fabric api 0.86.*

### ISSUE THREAD

**Issue by pesegolsson** [LambdAurora/LambDynamicLights#172]
**Describe the bug**
dynamic light not available when you update to fabric 0.86.*

**To Reproduce**
1. install latest fabric api

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.20.1
 - Fabric Loader version0.14.21-1.20.1
 - Mods [e.g. fabric-api v0.86.1, lambdynamiclights v2.3.1

**Comment by Insane-Owl** [comment]
It doesn't work for me either.

**Comment by Arae-1** [comment]
yep, doesn't work for me either
