### ISSUE TITLE
LambDynamicLights error in Fabric 0.85.0+1.20.1

### ISSUE THREAD

**Issue by NayaCcR** [LambdAurora/LambDynamicLights#173]
Latest.log is reporting the following errors:
 - Mod 'LambDynamicLights' (lambdynlights) 2.3.1+1.20.1 recommends version 0.19.1 or later of quilt_loader, which is missing!
	 - You should install version 0.19.1 or later of quilt_loader for the optimal experience.

You only state in the release that you need to use the Fabric loader from version 0.83.0 onwards, and don't mention the need to use the quilt_loader to make the module work.

**Comment by LambdAurora** [comment]
Recommendation isn't a requirement, the mod still works fine with Fabric loader.

**Comment by NayaCcR** [comment]
> 

But I can't start my game properly

**Comment by LambdAurora** [comment]
That message log specifically is unrelated to your issues.
