### ISSUE TITLE
Mobs + Items + Transparent blocks light up, but not the rest of the enviornment??

### ISSUE THREAD

**Issue by LemonBox2** [LambdAurora/LambDynamicLights#174]
On both single player and servers, the enviornment doesnt light up how it used to,
everything was fine two days ago, then it just broke.
Ive tried to uninstall and reinstall, but nothing i do seems to work.
I havent messed with any configuration or added any new mods before this broke
 
 
![2023-08-03_13 06 22](https://github.com/LambdAurora/LambDynamicLights/assets/141365792/d1c9520c-02be-4bff-b2ec-d9b4a1b4ad68)
![2023-08-03_13 06 18](https://github.com/LambdAurora/LambDynamicLights/assets/141365792/4384c03c-464b-4b37-8da3-04782dcb5
![2023-08-03_13 06 10](https://github.com/LambdAurora/LambDynamicLights/assets/141365792/3b60ffaa-a5d8-4945-8f89-79657c106509)
0d1)
![2023-08-03_13 05 35](https://github.com/LambdAurora/LambDynamicLights/assets/141365792/cf1a9113-ac36-4f3b-a7ee-4f62c98e3cb6)
![2023-08-03_13 05 43](https://github.com/LambdAurora/LambDynamicLights/assets/141365792/f11c55da-63fe-4cd5-b905-5f598fbef32f)
![image](https://github.com/LambdAurora/LambDynamicLights/assets/141365792/20fff1ce-24a3-4a33-925b-df1b31e4e808)

 - Minecraft 1.20.1 
 - Fabric Loader version (0.14.22)
 - Mods lambdynamiclights-2.3.1+1.20.1
 - Version Java

**Comment by Wondiws98** [comment]
Had the same issue. I reinstalled lambdynamiclights and installed [sodium](https://modrinth.com/mod/sodium/version/mc1.20-0.4.10). Not sure which one fixed it but it worked fine after.

**Comment by LucasWerner437** [comment]
Same here. For me the dynamic lights stopped working when I updated sodium to its latest version. 

LambDynamicLigths will work on 1.20.1 but only with sodium 0.4.10. It won't work with sodium 0.5.0 nor without it entirely.

**Comment by sandstripes** [comment]
Sodium 0.5 causes this issue, although it's not entirely just a Sodium 0.5 incompatibility because this issue was made before Sodium 0.5 was released and the mods list doesn't list Sodium

**Comment by Cookie-Kurokami** [comment]
I can confirm that I too am having this issue after upgrading to Sodium 0.5.

**Comment by Kichura** [comment]
Have you tried setting the `always-tesselate-blocks` to false in your indigo configuration file?

**Comment by LucasWerner437** [comment]
I personnally haven't changed any settings in Indigo and am using Indium along with sodium. I downgraded until a fix is published. 

Here is another issue, title fits the problem better I suppose : https://github.com/LambdAurora/LambDynamicLights/issues/175

@Kichura have you ? Did it have any effect ?

**Comment by Kichura** [comment]
> I personnally haven't changed any settings in Indigo and am using Indium along with sodium. I downgraded until a fix is published.
> 
> Here is another issue, title fits the problem better I suppose : #175
> 
> @Kichura have you ? Did it have any effect ?

Sodium 0.5 is a known issue and therefore indigo + indium can't fix it themselves.

**Comment by Cookie-Kurokami** [comment]
> Have you tried setting the `always-tesselate-blocks` to false in your indigo configuration file?

I tried this just a moment ago, and it did not change anything.

**Comment by Tursiops-G** [comment]
Note to Developer (Future Compatibility): This issue also occurs in the current 1.20.2 23w31a Snapshot (No Sodium version available yet), 

However, setting the **always-tesselate-blocks** to **false** in the /config/fabric/indigo-renderer.properties file fixes the problem, and then LambDynamicLights 2.3.1+1.20.1 works just fine. :)
(Except for the Settings Menu GUI, but that's a totally different issue for another time).
