### ISSUE TITLE
not working with quilt

### ISSUE THREAD

**Issue by Elllkere** [LambdAurora/LambDynamicLights#177]
**Describe the bug**
Using quilt loader and quilt api mod is loaded normally, but no adding dynamic lights, i still have darkness when im holding torch

**To Reproduce**
1. Start the game with quilt mod loader
2. Enter dark zone with torch in the hand

**Expected behavior**
Expected dynamic light like in screenshots

**Screenshots**
![image](https://github.com/LambdAurora/LambDynamicLights/assets/96520236/471f3ecb-b798-4d0f-907f-5b8e7f840692)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Minecraft 1.20.1
 - Quilt Loader version 0.19.2
 - Mods qfapi-7.1.1 qsl-6.1.1 fapi-0.86.1 mc-1.20.1, lambdynamiclights v2.3.1
 - Version 2.3.1
 - Branch mc1.20

**Additional context**
In modrinth says that mod is for fabric and quilt loaders if there is only fabric then please update information about it

**Comment by ghost** [comment]
Both Fabric _(0.14.22)_ and Quilt _(0.19.2, also appears on 0.20.0-beta 11)_ are having this issue for me as well.

Only entities and vegetation are illuminated by dynamic lights, however, the world blocks are unaffected.

It could be a driver issue?

**Comment by notandvm** [comment]
it's an issue with the recent sodium update: #175 

EDIT: seems the issue persists regardless of sodium's presence, my mistake
a temp fix that _should_ work (as long as sodium isn't present) is changing "always-tesselate-blocks" to false in config/fabric/indigo-renderer.properties

**Comment by Elllkere** [comment]
Duplicate of what ? It's not working with or not sodium, exactly on quilt. I installed only quilt api and this mod, no sodium or other and it's not wrking, if i switch it to fabric it's working normal

**Comment by LambdAurora** [comment]
The reason for it not working is due to either Sodium or either the used Fabric API version, which might be one of the most recent on Quilt, which also cause the issue.
