### ISSUE TITLE
Weird light behavior with sodium 0.5.X

### ISSUE THREAD

**Issue by itsfoxygold** [LambdAurora/LambDynamicLights#183]
Describe the bug
Light with sodium 0.5.1+ version is buggy: flickering and updating with big latency when player is moving even on fancy dynamic lights option. Also light is spreading in strange directions and has spots with unnatural brightness differences

To Reproduce
1. Pick up any object can emit light
2. Start moving
3. See bugs

Expected behavior
It was expected that the quality and behavior of the light would be the same as in previous versions of Sodium (with 0.5.0, 0.4.10 and older were anaffected of these issues, but with 0.5.1 and 0.5.2 dynamic light are buggy) 

Screenshots
(https://drive.google.com/file/d/1inQRSbDBpeK0udmNmGgoC_loYoy_RHnq/view?usp=sharing)

Desktop (please complete the following information):
 - OS: Windows 10 22H2
 - Minecraft: 1.20.1
 - Fabric Loader version: 0.14.22
 - Mods: sodium 0.5.2, sodium-extra 0.5.1, reeses-sodium-options 1.6.5, lambdynlights 2.3.2, fabric-api-0.88.1, modmenu 7.2.2
 - Version: 2.3.2
 - Branch: 1.20-1.20.1

Additional context
options: dynamic light: fancy (problem also persists in fast and fastest)
entities: on
block entities: on
first-person: on
Tried on both NVIDIA and AMD GPU

**Comment by Kichura** [comment]
This has been discussed via PR [#178] where light delays will occur when upgrading, in conclusion it is a confirmed visual bug.

**Comment by Robotomy101** [comment]
wait so the issue still hasn't been fixed right? because I'm experiencing the same thing too

**Comment by itsfoxygold** [comment]
> wait so the issue still hasn't been fixed right? because I'm experiencing the same thing too

Yes, this issue still hasn't been fixed. Tried newest version of sodium and LambDynamicLights. Also updated gpu drivers to the latest version (PC with nvidia 3070 gpu and laptop with amd igpu integrated in ryzen 5 4500U). And no changes, unfortunately

**Comment by LambdAurora** [comment]
Given this issue is still *somewhat* present with Sodium 0.6.X while not having any injection into Sodium, I'm tempted to say it's more of a Sodium issue.
I believe in Sodium 0.6.X the issue is less visible.
