### ISSUE TITLE
Compatibility with Bushier Flowers

### ISSUE THREAD

**Issue by SafeOfArsenal** [LambdAurora/LambDynamicLights#184]
**Is your feature request related to a problem? Please describe.**
Yea, Bushier Flowers has bushy toch flowers that do not glow

**Describe the solution you'd like**
bushy torchflower = glow

**Describe alternatives you've considered**

**Additional context**

**Comment by LambdAurora** [comment]
I do not understand your request, if the goal is to make the item of another mod glow in your hand then this already can be done by creating a resource pack as described [here](https://github.com/LambdAurora/LambDynamicLights/blob/1.20.2/API.md#item-light-sources).
