### ISSUE TITLE
Top of hopper is not lighted up when mod Continuity is installed

### ISSUE THREAD

**Issue by icynstant** [LambdAurora/LambDynamicLights#185]
With Continuity:
![2023-09-24_15 56 48](https://github.com/LambdAurora/LambDynamicLights/assets/127024748/f3e49a77-afb6-47ad-9b53-ee0710999a41)

Without Continuity:
![2023-09-24_15 58 05](https://github.com/LambdAurora/LambDynamicLights/assets/127024748/2f8bc86c-d7ee-450f-b610-7358c4a4c3c4)

 - OS: Windows 10
 - Minecraft 1.20.1
 - Fabric Loader version 0.14.22
 - Mods: Screenshot below
 - Version 2.3.2+1.20.1
 - Branch (Idk what's that)

![Screenshot_1](https://github.com/LambdAurora/LambDynamicLights/assets/127024748/e592f185-8112-4259-8503-829b93c59c71)

Looks like resource packs "Stay True" and "Clear Glass with Connected Textures" are causing this issue.

**Comment by icynstant** [comment]
My bad, I forgot to test it without resource packs. I may fix it by myself.

**Comment by BluSpring** [comment]
Can reproduce using doors, I believe this is caused whenever Continuity is activated in general.
![image](https://github.com/LambdAurora/LambDynamicLights/assets/20620191/2f9bdf6f-2dd5-4f89-8a18-92025a7f0676)

Mods:
![image](https://github.com/LambdAurora/LambDynamicLights/assets/20620191/190f6375-fe28-4014-ad18-14c625865c31)

However, this seems to only occur when Sodium is installed, which leads me to believe my Sodium fix commit (https://github.com/LambdAurora/LambDynamicLights/commit/8c2c0107d75b5a853690f8d5ec093d501a0aee90) is acting up for Continuity specifically.

**Comment by BluSpring** [comment]
After further investigation, this isn't exclusive to Continuity, rather it's Indium when "Always Tesselate Blocks" set to true (which would be active when Continuity is installed).
