### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by thrasos-dev** [LambdAurora/LambDynamicLights#190]
**Describe the bug**
Someone from our server was reporting crashes caused by LambDynamicLights.

**To Reproduce**
They are claiming that the game was crashing every time they started the game.

**Crash Report**
https://haste.unbelievaboat.com/1161596992145719597.md

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Minecraft [1.20.1]
 - Fabric Loader version [0.14.22]
 - Mods [Fantasy MC Modpack]
 - Version [2.3.2]

**Comment by LambdAurora** [comment]
The configuration file is corrupted and should be reset (by deletion).
(Alternatively it can be attempted recovery by deleting duplicate entries).

**Comment by thrasos-dev** [comment]
Will do thanks!
