### ISSUE TITLE
Issue: LDL 2.3.1 not working on 1.19.4, Fabric API 0.87.2, no sodium

### ISSUE THREAD

**Issue by iMiluum** [LambdAurora/LambDynamicLights#196]
**Describe the bug**
LDL doesn't light up the environment

**To Reproduce**
1. Use a fresh instance with only Fabric API 0.87.2 and LDL 2.3.1 on Minecraft 1.19.4
2. Create any world
3. `/time set night`
4. Equip torch
5. Darkness

**Expected behavior**
Not darkness

**Screenshots**

![image](https://github.com/LambdAurora/LambDynamicLights/assets/84710831/f87a2f7d-98fa-4eab-b225-02c3a909b7b8)
![2023-11-15_15 13 47](https://github.com/LambdAurora/LambDynamicLights/assets/84710831/48fc21d2-e488-48d6-894c-978c2e0cf795)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.19.4
 - Fabric Loader version 0.14.24
 - Mods: Fabric API 0.87.2, Lambdynamiclights 2.3.1
 - Version 2.3.1
 - Branch: unknown, downloaded from Modrinth release

**Additional context**
I'm trying to develop a mod with "glowing" items. It works perfectly on 1.19.2, but sadly it doesn't light up at all in 1.19.4

**Comment by iMiluum** [comment]
Closing this as duplicate of #181.

Solution:
https://github.com/LambdAurora/LambDynamicLights/issues/181#issuecomment-1706055518

**Comment by iMiluum** [comment]
Solution doesn't apply to 1.19.4 as the artifact only works on 1.20+

**Comment by LambdAurora** [comment]
This was caused by a change in Fabric API, 1.19.4 is not supported anymore though.
