### ISSUE TITLE
Possible amethyst shards addition

### ISSUE THREAD

**Issue by TooMuchHuke** [LambdAurora/LambDynamicLights#198]
Currently, amethyst shards aren't affected by LambDynamicLights, but the blocks that drop the shards do, so the shards should emit a low amount of light, 1 or 2 levels would make sense, as the small amethyst bud releases 2. If you wanted to go the extra mile, a config like More Composting (https://modrinth.com/mod/more-composting) would work well, but I understand that could be difficult

**Comment by LambdAurora** [comment]
This already is possible through a resource-pack, please refer to the documentation.
