### ISSUE TITLE
Crash on fabric 1.16.1 custom modpack

### ISSUE THREAD

**Issue by NxD136** [LambdAurora/LambDynamicLights#2]
Hello,

There is an issue loading your mod in my custom modpack. 

Important Details : Fabric version (v0.8.8+build.202) ; Fabric API version (v0.14.1+build.372-1.16) ; LambDynamicLights version (fabric-1.1.0+1.16.1).

Crash Report : 
[crash-2020-07-08_19.45.09-client'ltr'(lambdynamiclights).txt](https://github.com/LambdAurora/LambDynamicLights/files/4893746/crash-2020-07-08_19.45.09-client.ltr.lambdynamiclights.txt)

Could be possible that it's a conflict with another mod or perhaps a lack of libraries? If so, could you help me pinpoint which one? There should be a mod list on the crash report itself. 

I will reply shortly, testing it by itself for a possible crash report without any possible conflicting by other mods and/or API/libraries.

Regards,
- Retro

**Comment by LambdAurora** [comment]
Hello, can you please check if the crash is still happening with the latest version? (1.2.0+1.16.1)
https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights/files/2999843

**Comment by NxD136** [comment]
Just did, forgot to check for updated version, downloaded the latest one last night so I did not think it would be updated yet lol.

Everything works fine now, thanks!
-Retro
