### ISSUE TITLE
1.20.3/4 Support

### ISSUE THREAD

**Issue by R00tB33rMan** [LambdAurora/LambDynamicLights#200]
**Is your feature request related to a problem? Please describe.**
As many are you are likely aware, 1.20.3/4 just released. Unfortunately, this mod fails to load on the latest iteration of Minecraft.

**Describe the solution you'd like**
1.20.3/4 Support Compatibility

**Describe alternatives you've considered**
Potential Fork/PR from a contributor.

**Additional context**
Thank you for your hard work and dedication towards keeping this mod compatible with the latest versions of Minecraft. Your work doesn't go unnoticed and am very impressed with all of the efforts you've committed so far!

**Comment by joestr** [comment]
I'm *really* new into client modding but I managed to get it working. [Here](https://cloud.joestr.at/s/gncHpcP2Q3Q8xgy) is compiled preview with the changes.

**Comment by R00tB33rMan** [comment]
> I'm _really_ new into client modding but I managed to get it working. [Here](https://cloud.joestr.at/s/gncHpcP2Q3Q8xgy) is compiled preview with the changes.

Works nicely! Don’t have any compatibility issues with your latest iteration. Thank you for giving this a whirl and succeeding. We appreciate your interest in taking a few minutes out of your day to convenience others looking to utilize this wonderful mod. 😀

**Comment by Crystal-Spider** [comment]
Would be awesome to have an official version to ship it in modpacks
