### ISSUE TITLE
fabric version 0.83.0-1.20 doesn't exist

### ISSUE THREAD

**Issue by DoriteLover** [LambdAurora/LambDynamicLights#201]
**Describe the bug**
Dear developer
Hello. I'm having a problem with my minecraft survival, I'm so tried of holding a useless torch, so I go to google
 and i found your mod which is great i guess but when i open the game it say require version 0.83.0-1.20 fabric version which dont exist so please fix it
**To Reproduce**
![image](https://github.com/LambdAurora/LambDynamicLights/assets/148433928/2d7095ac-4ffe-449b-8a90-d9a4de0a7c78)

**Expected behavior**
a crash message

**Screenshots**
![image](https://github.com/LambdAurora/LambDynamicLights/assets/148433928/22aefb79-8222-4fda-b2d4-8a09c7697ee8)

**Desktop:**
 - OS: Windows 10 22H2 expired
 - Minecraft 1.20.1
 - Fabric Loader version 0.15.1-1.20.1
 - Mods 
![image](https://github.com/LambdAurora/LambDynamicLights/assets/148433928/00c70e88-c65b-461d-a545-5e2a83f5646b)

 - Version 2.3.2=1.20.1
 - Branch sorry i dont know what this mean

**Comment by LambdAurora** [comment]
Install [Fabric API](https://modrinth.com/mod/fabric-api).
