### ISSUE TITLE
Less Armor Glow/Light doesnt affect Armor?

### ISSUE THREAD

**Issue by GrevaProgramming** [LambdAurora/LambDynamicLights#205]
Hello, I was just wondering if you could code a way it could make the armor glow less. I find the armor glow to be distracting, particularly in caves with a shader running. I would appreciate a way to adjust the effect the glow has on armor, or a way to just not make the handheld light sources affect armor. Thanks!!
PS. Im on 1.20.2

**Comment by LambdAurora** [comment]
This should be fixed by using the self light source setting.
