### ISSUE TITLE
Disable dynamically light particle config setting (To stop lag)

### ISSUE THREAD

**Issue by borisshoes** [LambdAurora/LambDynamicLights#206]
**Is your feature request related to a problem? Please describe the solution you'd like**
It would be great if the config has a way to disable dynamic lighting for either all particles or have a list of configurable dynamic particles similar to the block and entity config list currently implemented.

Playing on servers that make use of a lot of particle effects for things like minigames can obliterate frames even with a decent graphics card (I use a GTX 1080). 

**Describe alternatives you've considered**
Disabling particles is a bit of a non-starter since servers can force them to be displayed on decreased/minimal settings and they often provide key visuals in game modes.
I've also tried tweaking the current config settings to see if they affect the particle rendering.

**Additional context**
Here's a client spark profiler report just to verify that it is lamb's dynamic particle rendering that is causing the lag:

![image](https://github.com/LambdAurora/LambDynamicLights/assets/3745238/253a7ff7-e3b9-4055-bd96-42776e227531)

**Comment by LambdAurora** [comment]
Due to how the injection is made I cannot selectively disable particles specifically.

But I plan on looking into optimizing light lookups.

**Comment by LambdAurora** [comment]
This issue should be heavily alleviated with LambDynamicLights 3.1.0 which contains new optimizations.

**Comment by borisshoes** [comment]
Can confirm, the latest version fixes the lag problem! Thanks!
