### ISSUE TITLE
Flickering chests when used with a Fabric 1.20.1 modpack

### ISSUE THREAD

**Issue by thelyric27** [LambdAurora/LambDynamicLights#207]
I started playing the Prominence RPG modpack, and added LambDynamicLights to it along with Radiant Gear and a mod that enables lanterns to be equipped in the Trinkets mod's belt slot, because I just love having a lantern on my belt to dynamically light my surroundings as opposed to carrying multiple stacks of torches to place them everywhere I go. Though I noticed that the lighting on chests, and presumably other similar blocks (like bells, which I noticed while typing. tile entities?), flickers rapidly when moving near them with a light source in hand. I'm not sure what part of the pack might cause the issue, but I started by disabling shaders, then disabling the mod to see if i could tell if there was another dynamic lighting feature causing interference, which there wasn't, then I re-enabled LDL and disabled Vivecraft and it's dependents, unfortunately to no avail.

To Reproduce:

1. Load Prominence RPG Fabric 1.20.1 with the most recent version of LDL.
2. Start a new world with the bonus chest enabled. 
3. Take the chest to shade and walk around it with a torch in hand.

 - OS: Linux Mint 21.1 'Vera'
 - Graphics: AMD Radeon RX 6600 XT (navi23, LLVM 15.0.7, DRM 3.42, 5.15.0-91-generic)
 - Minecraft 1.20.1
 - Fabric Loader version 0.15.6
 - Mods: Prominence RPG + LambDynamicLights
 - Version 2.3.2
 - Branch 1.20

**Comment by Fyoncle** [comment]
I would this is because of EBE

**Comment by LambdAurora** [comment]
This can indeed be caused by a combination of Enhanced Block Entities, LambDynamicLights, Sodium, and Indium.

Not sure what I could do on my side as it'd require to heavily modify a FRAPI implementation, and with Sodium 0.6 the issue is not present anymore (though this is not relevant for Minecraft 1.20).
