### ISSUE TITLE
Support for Block and Item Display

### ISSUE THREAD

**Issue by dhouck** [LambdAurora/LambDynamicLights#209]
**Is your feature request related to a problem? Please describe.**
Item and block display entities often seem like they should emit light, but they donʼt have hand or armor slots so you canʼt just give them something glowing.

**Describe the solution you'd like**
Block and item display entities should emit light appropriate for the block or item they are displaying.

**Describe alternatives you've considered**
A more general NBT tag for all entities to override dynamic light would also solve this problem in particular, but seems like it should be a separate feature; technically that can solve *all* problems with various entities, but display entities should still by default emit appropriate light.

**Additional context**

**Comment by LambdAurora** [comment]
Added in LambDynamicLights v4.0.0!
