### ISSUE TITLE
Add support to add custom blocks/items to the list of light blocks

### ISSUE THREAD

**Issue by WildFyr16** [LambdAurora/LambDynamicLights#210]
**Is your feature request related to a problem? Please describe.**
No real issue, just the fact that not all blocks/items have the ability to be turned dynamic.

**Describe the solution you'd like**
This would allow people to add any items or blocks not only from Minecraft, but also any mod that they would want to add dynamic lights to as well. That way a lot of this suggestions to "add support for X mod" can simply be fixed by the user themselves. This would work just like the existing toggle in the menu, expect at the top have an option to either select a block/item, or manually enter the block/items ID (minecraft:stone or modname:itemname)

**Describe alternatives you've considered**
I mean the only real alternatives would be to modify the jar file to include more options for blocks/items.

**Additional context**
N/A

**Comment by BluSpring** [comment]
This actually already exists if you create a custom resource pack:
https://github.com/LambdAurora/LambDynamicLights/blob/1.17/API.md#item-light-sources
