### ISSUE TITLE
1.20.6 Support

### ISSUE THREAD

**Issue by iWisp360** [LambdAurora/LambDynamicLights#216]

**Comment by Mukul1127** [comment]
Temporarily you can use RyomaticLights, it's a architectuary port of LambDynamicLights that happens to already support 1.20.6

**Comment by TechySC23** [comment]
When the hell would @LambdAurora release the 1.20.6 and 1.21 versions of LambDynamicLights?

**Comment by LambdAurora** [comment]
1.20.6 will be skipped in favor of 1.21.
