### ISSUE TITLE
on flashyreese sodium 1.16.2 fork, entities don't light up even though dynamic light is around them

### ISSUE THREAD

**Issue by ghost** [LambdAurora/LambDynamicLights#22]
https://i.imgur.com/334BmZl.png

creeper is detonating, its hard to tell in the picture. notice how the lava im holding is dark.

**Comment by LambdAurora** [comment]
I don't do support for unofficial forks.

This fork is based of the stable branch, LambDynamicLights have a fix for dev branch not stable for 1.16.2
