### ISSUE TITLE
Lightning bug. Anoying.

### ISSUE THREAD

**Issue by invilutzu** [LambdAurora/LambDynamicLights#221]
Lightning not working as it should!

I expected the torch in my hand to light up around me. It did for a while and after a restart the mod broke and it light only my skin and not the surroundings.

![image](https://github.com/LambdAurora/LambDynamicLights/assets/172993108/f2dae5da-3103-4699-994d-bd1ec1cdcbfd)

 - OS: Windows 10
 - Minecraft fabric 1.20.1
 - Fabric Loader version 0.15.11
 - Mods 
 
![image](https://github.com/LambdAurora/LambDynamicLights/assets/172993108/20581f20-b613-453a-8e14-a9f7a9e03c34)

 - Version 1.20.1
 - Branch mc1.20.1

**Additional context**
ive tried everything to reinstalling mods and stuff. IT DOESNT WORK. FIX IT !

**Comment by LambdAurora** [comment]
If restarting broke something then you've either added or removed a mod.
Please make sure to check the settings as well.

**Comment by vinnyg0621** [comment]
anoying is not a word.

**Comment by invilutzu** [comment]
Fuck you, Americans, y’all think you are the only nation on the globe? English is not my native language so stop being such a shithead and help users Sent from my iPhoneOn 23 Jul 2024, at 07:06, Vinny Gregory ***@***.***> wrote:﻿
anoying is not a word.

**Comment by vinnyg0621** [comment]
> Fuck you, Americans, y’all think you are the only nation on the globe? English is not my native language so stop being such a shithead and help users Sent from my iPhoneOn 23 Jul 2024, at 07:06, Vinny Gregory ***@***.***> wrote:﻿ anoying is not a word. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

i mean, it's spelled annoying

**Comment by XandarNull** [comment]
> Fuck you, Americans, y’all think you are the only nation on the globe? English is not my native language so stop being such a shithead and help users Sent from my iPhoneOn 23 Jul 2024, at 07:06, Vinny Gregory ***@***.***> wrote:﻿ anoying is not a word. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Also, you meant lighting not lightning, I'm not American but I still try to speak well and don't get angry if someone corrects my spelling, the guy didn't mean to insult you, it's just your spelling is kinda... _Annoying_

**Comment by LambdAurora** [comment]
Ok y'all won, I'm locking this issue.

Is it this hard to be mature on an issue tracker?
This is **not** some random social network where you can freely post your thoughts.

This is **an issue tracker**, made to track issues so I can fix bugs or add new features, or provide support to users when they have a problem with the mod. The only comments that should be posted are comments that provide constructive feedback on the issue itself, not some petty war on spelling or grammar.

**Comment by LambdAurora** [comment]
Looking back at it, the issue was that the mod was paired with a version of Sodium which was incompatible at the time.
Updating to LambDynamicLights 2.3.2 would have fixed the issue.
