### ISSUE TITLE
Incompatible with Vulkan mod

### ISSUE THREAD

**Issue by Dann50** [LambdAurora/LambDynamicLights#238]
**Describe the bug**
Dynamic lights do not work with vulkan mod (visuals)

**To Reproduce**
1. download vulkan mod
2. download lambdynamiclights
3. join world
4. no dyn lighting

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft [e.g. 1.16.4]
 - Fabric Loader version : 0.16.5
 - Mods : fabric api, vulkan and lambdynlights
 - Version 1.21

**Additional context**
not crash related

**Comment by LambdAurora** [comment]
Terrain is indeed not lit up.

This is most likely due by Vulkan Mod not using `LevelRenderer.getLightColor` directly and instead re-implementing their own function. Update: not likely, basically confirmed, they're using Sodium's 0.5 lighting pipeline.

Honestly at this point, seeing Sodium and other similar rendering mods are well capable of using that method directly, which even allowed me to vastly reduce Sodium-specific code in latest versions of LambDynamicLights, I'm not going to add more fragile injection points into other rendering mods.

Please bring this up directly to Vulkan Mod developers.
