### ISSUE TITLE
Crash with Continuity (1.21)

### ISSUE THREAD

**Issue by BluSpring** [LambdAurora/LambDynamicLights#239]
**Describe the bug**
When launching with Continuity installed, the game will crash.

**To Reproduce**
1. Install LDL
2. Install Continuity
3. Launch the game

**Expected behavior**
The game launches fine.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft: 1.21.1
 - Fabric Loader version: 0.16.5
 - Mods: Fabric API 0.105.0+1.21.1, Continuity 3.0.0-beta.5+1.21, Sodium 0.6.0-beta.2+mc1.21
 - Version: 3.0.0+1.21.1
 - Branch: 1.21

**Additional context**
This crash is caused by a call in [LambDynLightsMixinPlugin](https://github.com/LambdAurora/LambDynamicLights/blob/1.21/src/main/java/dev/lambdaurora/lambdynlights/LambDynLightsMixinPlugin.java#L37) towards LambDynLights.java, which [initializes the Identifier](https://github.com/LambdAurora/LambDynamicLights/blob/1.21/src/main/java/dev/lambdaurora/lambdynlights/LambDynLights.java#L60), which causes mixins to Identifier to fail.

**Comment by LambdAurora** [comment]
Should be fixed in LambDynamicLights 3.0.1.
