### ISSUE TITLE
Dynamic light does not affect handheld items

### ISSUE THREAD

**Issue by MeeniMc** [LambdAurora/LambDynamicLights#24]
When hodling a torch in-hand, the 'lightlevel' of the handheld torch item will reflect ambient light, rather than being set to 15 (the item being a torch!). Same thing happens to the item held in  the other hand. 

MC 1.16.3, LambDynamicLights 1.3.1, Sodium 0.1.0, Phosphor 0.6.0

**Comment by LambdAurora** [comment]
Can you please provide a screenshot or a video highlighting what you're describing?

I'm not sure what happens.

**Comment by MeeniMc** [comment]
Initial report is not quite correct, the problem is weirder. The brighness of the hand-held item is not dependent upon ambient brightness, but on player orientation (why?!!). 

(Test done w/o Phosphor/Sodium here, same would happen with Phosphor/Sodium).

**case 1: In-hand torch is dim:**
![2020-09-30_15 37 19](https://user-images.githubusercontent.com/68366846/94731556-f9da1800-0332-11eb-8eba-6393a4ecf030.png)

**case2: in-hand torch brightness varies with player orientation**; player is at the same block position, but only looking approx 90 degrees rotated. Brightness variation is repeatable with player orientation.
![2020-09-30_15 37 26](https://user-images.githubusercontent.com/68366846/94732076-c5b32700-0333-11eb-8ba3-a806cb3c94f7.png)

**case3: torch on the wall is bright yellow in all orientations, in-hand torch is still dim despite ambient lightlevel 15:**
![2020-09-30_15 37 44](https://user-images.githubusercontent.com/68366846/94731628-1a09d700-0333-11eb-92cf-f101b3bf6648.png)

**Comment by MeeniMc** [comment]
**Same issue w/o a texture pack:**
![2020-09-30_15 50 18](https://user-images.githubusercontent.com/68366846/94732761-ae286e00-0334-11eb-9705-0fcc8b2f85f1.png)

**Same issue with Vanilla mc1.16.3 (no mods!)**
![2020-09-30_15 52 46](https://user-images.githubusercontent.com/68366846/94732977-09f2f700-0335-11eb-8766-a43da9e890f7.png)


At this point I do no view it as a bug in you mod, since Vanilla does the same thing. It's more a feature request: you should pump-up the rendering lightlevel of emissive handheld items to whatever lightlevel they produce (so 15 for a torch).

**Comment by LambdAurora** [comment]
So, here's it's entity rendering and light level (yeah, even in first person render the held item is part of the entity rendering).

In theory the same thing could happen with a fox holding a torch with different view angle. (or any mob holding a light for the matter).

Though, this is quite weird and might be strongly Vanilla related.

The code I have will always try to set the entity luminance with higher priority than any other light level. In the case of a torch the luminance value is `14` (from Vanilla code), so unless there's even a brighter light source (like fire or lava) it should be very consistent and stay at 14 at all time.

The fact it darkens is very weird.

**Comment by MeeniMc** [comment]
I am doing some cleanup on my pending issues/prs because I have too many opened.

This is vanilla equivalent so out of scope of the mod IMO.
