### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Kloytz** [LambdAurora/LambDynamicLights#240]
**Describe the bug**
Crashed at start after installing newest lambdynamiclight mod

**To Reproduce**
Installed dynamic lights for 1.21.1

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Minecraft 1.21.1
 - Fabric Loader version 0.16.5
 - Mods (a lot...)

**Additional context**
[crash-2024-10-09_21.31.59-client.txt](https://github.com/user-attachments/files/17321014/crash-2024-10-09_21.31.59-client.txt)

**Comment by LambdAurora** [comment]
Was resolved on Discord.

Seems to be caused by backslot and there's no evidence the crash is in itself due to LambDynamicLights.

**Comment by Rtful** [comment]
@LambdAurora Sorry to chime in on a closed issue but I am experiencing the same issue. I understand that the bug crash does not occur because of LambDynamicLights but I am nontheless interested in the solution that fixed it.
