### ISSUE TITLE
Sculk sensors and sculk catalysts not properly lit up

### ISSUE THREAD

**Issue by SPINZ1** [LambdAurora/LambDynamicLights#241]
**Describe the bug**
The sides and bottom of sculk sensors, and all sides of the sculk catalyst, do not get lit up by dynamic lighting

**To Reproduce**
1. Build a dark room around the player.
2. Place the sculk sensors (both normal and calibrated) and sculk catalyst in the room.
3. Hold a dynamic light source.

**Expected behavior**
All parts of the above blocks should be lit.

**Screenshots**
![image](https://github.com/user-attachments/assets/5bb90057-018d-41ef-995f-3aaaa2424d80)
![image](https://github.com/user-attachments/assets/603caf19-8f90-4500-9985-2dabd5e73178)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.21
 - Fabric Loader version 0.16.7
 - Mods: animatica-0.6.1+1.21, ArmorTrimItemFix-fabric-1.21-1.1.0, AxesAreWeapons-1.9.1-fabric-1.21, axolotlbuckets-1.2.0+1.21, BetterAdvancements-Fabric-1.21-0.4.2.16, better-clouds-1.7.4+1.21-fabric, bettermounthud-1.2.4, BoatBreakFix-Universal-1.0.2, citresewn-1.2.1+1.21, CloseRecipeBook-1.1+1.20.6, cloth-config-15.0.140-fabric, Clumps-fabric-1.21-18.0.0.2, continuity-3.0.0-beta.5+1.21, cubes-without-borders-2.1.1+1.21, cut-stone-for-cobble-1.0.1, DatapackInstaller-2.0.0, Debugify-1.21+1.0, deslabification-1.1.0+1.21+fabric, eating-animation-1.21+1.9.72, eg_fix_horizontal_camera_lag-1.1.1-fabric-mc1.20.6, enhancedblockentities-0.10.1+1.21, entity_model_features_fabric_1.21-2.2.6, entity_pin_cushions-fabric-1.21-1.0, entity_texture_features_fabric_1.21-6.2.5, entityculling-fabric-1.7.0-mc1.21, essential_1-3-4-1_fabric_1-21-1, fabric-api-0.102.0+1.21, fabric-language-kotlin-1.12.2+kotlin.2.0.20, fabrishot-1.14.1, fasterrandom-5.1.0, fastquit-3.0.0+1.20.6, ferritecore-7.0.0-fabric, flow-2.1.2+1.21, Fog-fabric-1.4.1-1.21.1, fzzy_config-0.5.2+1.21, ImmediatelyFast-Fabric-1.2.21+1.21.1, indium-1.0.35+mc1.21, iris-1.7.3+mc1.21, lambdynamiclights-3.0.1+1.21.1, language-reload-1.6.1+1.21, leatherbundle-2.1.0, lithium-fabric-mc1.21-0.13.1, main-menu-credits-1.2.0, make_bubbles_pop-0.3.0-fabric-mc1.19.4-1.21, mixintrace-1.1.1+1.17, modelfix-1.21-1.6-fabric, modernfix-fabric-5.19.1+mc1.21, modmenu-11.0.2, morechathistory-1.3.1, MouseTweaks-fabric-mc1.21-2.26, MRU-1.0.2+1.21+fabric, Necronomicon-Fabric-1.6.0+1.21, no-beacon-particles-1.0+1.21, noisium-fabric-2.3.0+mc1.21-1.21.1, notenoughanimations-fabric-1.7.6-mc1.21, nvidium-0.3.1, ObsidianUI-fabric-0.2.7+mc1.21, optigui-2.3.0-beta.6+1.21, owo-lib-0.12.15+1.21, particle_core-0.2.5+1.21, particle-rain-2.1.4, particular-1.1.1+1.21, puzzle-fabric-2.0.1+1.21, reeses_sodium_options-1.7.3+mc1.21, rrls-5.0.7+mc1.21-fabric, rsls-1.1.4, ScalableLux-0.1.0+fabric.26c6e72-all, shulkerboxtooltip-fabric-5.1.1+1.21, skinlayers3d-fabric-1.6.7-mc1.21, smeltingstone-1.21.1-0-fabric, sodium-extra-0.5.7+mc1.21, sodium-fabric-0.5.11+mc1.21, soundcontroller-1.1.3, status-effect-bars-1.0.6, tia-fabric-1.21-1.2.1, visuality-0.7.7+1.21, wakes-0.2.5+1.21, waveycapes-fabric-1.4.10-mc1.21, YetAnotherConfigLib-3.5.0+1.21-fabric, yosbr-0.1.2
 - Version 3.0.1
 - Branch 1.21

**Additional context**
I've found that the issue is a conflict between continuity and something else, but I've gone through all my other mods and couldn't figure out the other half of the problem.

**Comment by SPINZ1** [comment]
Also noticing this for falling block entities

**Comment by LambdAurora** [comment]
I've tried various combinations of this mod list and I cannot reproduce these issues.

One mod I cannot attempt to test with is Nvidium due to the lack of Nvidia GPU in my computers at the moment, maybe try without it?

Your last solution is to try to isolate the set of mods that's causing the issues by performing [a binary search](https://en.wikipedia.org/wiki/Binary_search) (aka yeet half your mods and see if the issue is still here, repeat until the issues go away, this allows to remove from the search mods that are not causing the issues fast).
