### ISSUE TITLE
Modrinth page states that v2.3.3 is compatible with MC 1.20.1 despite the .jar only being compatible with 1.20.2+

### ISSUE THREAD

**Issue by ARitz-Cracker** [LambdAurora/LambDynamicLights#245]
**Describe the bug**
- My modpack for my server is distributed using a custom packwiz compatible server with auto updates.
- https://modrinth.com/mod/lambdynamiclights/versions?g=1.20.1 lists `2.3.3+1.20.2` to be compatible with Minecraft 1.20.1, which is not.

**To Reproduce**
1. Go to modrinth page
2. Blindly download the latest version apparently compatible with 1.20.1
3. Have Minecraft fail to launch on startup

**Expected behavior**
The compatibility listing on the modrinth page match what's expected of the jar

**Screenshots**
N/A - Issue is self-descriptive

**Desktop (please complete the following information):**
 - OS: Any
 - Minecraft 1.20.1
 - Fabric Loader version: 0.16.5
 - Mods N/A - Issue is self-contained
 - Version 2.3.3+1.20.2
 - Branch: unknown

**Additional context**

**Comment by LambdAurora** [comment]
Fixed it, I might have forgotten that 1.20.2 is a bit special and I got induced in error by a previous version of LambDynamicLights that was marked compatible.
