### ISSUE TITLE
Does not run on Quilt.

### ISSUE THREAD

**Issue by Wintecks** [LambdAurora/LambDynamicLights#246]
**Describe the bug**
Does not run on Quilt.

**To Reproduce**
1. Run minecraft with this mod and Quilt.
2. All

**Expected behavior**
Еhat this mod will run on Quilt.

**Screenshots**
![image](https://github.com/user-attachments/assets/44e4659c-c93a-4df5-bd7d-3883f817c1b0)

**Desktop
 - OS: Windows
 - Minecraft 1.21
 - Quilt Loader version 0.26.4
 - Mods lambdynamiclights-3.1.2+1.21.1.jar fabric-api-0.100.6+1.21.jar (there are a lot of them, but if necessary, I can reset the archive.) 

**Additional context**
[crash-2024-10-29_19.52.30.8430-quilt_loader.txt](https://github.com/user-attachments/files/17561204/crash-2024-10-29_19.52.30.8430-quilt_loader.txt)

**Comment by LambdAurora** [comment]
Update to the latest Quilt Loader (including beta versions) or something.
