### ISSUE TITLE
Wind charges emit light

### ISSUE THREAD

**Issue by PrivateYT-AG** [LambdAurora/LambDynamicLights#247]
**Describe the bug**
When you throw a wind charge, it emits light as it moves.

**To Reproduce**
1. Get a wind charge
2. Throw it
3. The wind charge emits light

**Expected behavior**
The wind charge does not emit light as it moves.

**Screenshots**
![image](https://github.com/user-attachments/assets/7d42db84-f194-4f8c-82ff-3689908d1af0)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.21.3
 - Fabric Loader version 0.16.7
 - Mods fabric-api-0.106.1+1.21.3
 - Version v3.2.1+1.21.3
 - Branch mc1.21

**Comment by LambdAurora** [comment]
This is already fixed in the 3.2.2 release of the mod!
