### ISSUE TITLE
Dynamic Lighting

### ISSUE THREAD

**Issue by Tadxshiraa** [LambdAurora/LambDynamicLights#251]
The mod doesn't working, the dynamic lights doesn't shows up. I'm already checked everything and setted up properly, but the dynamic lights doesn't shows up.
![Screenshot_20241124_202017_Zalith Launcher](https://github.com/user-attachments/assets/50da179c-8aab-42b1-b7cc-96e0951cada9)
![Screenshot_20241124_202238_Zalith Launcher](https://github.com/user-attachments/assets/1dee0333-c013-4c52-bd00-d7fbed8cfbf2)

**Comment by LambdAurora** [comment]
Please provide logs and a mod list (unless it is visible in the logs), without this important information I will not be able to provide support.

**Comment by LambdAurora** [comment]
Given it's been a while and I haven't gotten any additional information to be able to provide support I will be closing this issue.

You still can provide the missing information and I'll re-open the issue if such information is provided.
