### ISSUE TITLE
[Question] Is this mod client-side, server-side or both?

### ISSUE THREAD

**Issue by Jarfeh** [LambdAurora/LambDynamicLights#27]
I was wondering, as I'm currently trying to use the sodium mod, and I was hoping to use this on a server without the mod installed

**Comment by LambdAurora** [comment]
It's literally one of the first badge in the description.

![env client](https://img.shields.io/badge/environment-client-1976d2?style=flat-square)

So yes, it's client side.

**Comment by Jarfeh** [comment]
Apologies, I did not notice the badge. Thank you!
