### ISSUE TITLE
[DELETE] This is not an issue I just wanted to send you a message

### ISSUE THREAD

**Issue by ghost** [LambdAurora/LambDynamicLights#29]
I think like a year back or so I asked if someone would port the dynamic lights library to fabric because I had looked at the code and it was totally over my head and I didn't feel like doing it, but then today I saw that someone actually did it. I was reading through the code and the explanation and I was so happy because you implemented it in exactly the way that I wanted, and also I didn't have to do it. So basically, thank you. You really made my day I'm so happy right now :P

**Comment by machinesmith42** [comment]
Close this issue please

**Comment by supsm** [comment]
If you want to chat more you can join the discord server: https://discord.gg/abEbzzv
