### ISSUE TITLE
When connecting to a dedicated server, the water sensitivity check does not work

### ISSUE THREAD

**Issue by calloatti** [LambdAurora/LambDynamicLights#3]
MC 1.1.61

lambdynamiclights-fabric-1.2.2+1.16.1.jar

Connecting to a dedicated server, the setting **water sensitivity check** has no effect, even when its ON, torches always work underwater.

**Comment by LambdAurora** [comment]
That's worrying, maybe it's the data tag.
If it's the data tag I'll be a bit disappointed then, thought it was a good idea to use it :/

**Comment by LambdAurora** [comment]
Fixed in dev, will soon publish a release including it :)

**Comment by LambdAurora** [comment]
Fixed in LambDynamicLights 1.3.0!
