### ISSUE TITLE
Not allowing to use mod

### ISSUE THREAD

**Issue by Markussthepug** [LambdAurora/LambDynamicLights#35]
I downloaded it and used forge in the launcher
![WhatsApp Image 2020-11-08 at 09 31 42](https://user-images.githubusercontent.com/74133881/98461606-74554d80-21a5-11eb-9592-3a3b3a966be3.jpeg)
 to try login to minecraft i got to the point that it said that the mod has some sort of fault

**Comment by LambdAurora** [comment]
This is a Fabric mod, you need [Fabric modloader](https://fabricmc.net/) and Fabric API to use this mod.

This mod will not work on Forge.
