### ISSUE TITLE
Crashes when saving world.

### ISSUE THREAD

**Issue by K0-RR** [LambdAurora/LambDynamicLights#36]
https://hatebin.com/jbeicnjrqs
 - OS: Linux
 - Minecraft 1.16.4
 - Fabric Loader version 0.10.6+build.214
 - fabric-api v0.25.4

**Comment by adri326** [comment]
That's... a lot of mods. Could you try to reproduce this bug with less mods as to reach a minimal case?

**Comment by LambdAurora** [comment]
Using #41 as main issue for this type of crash.
