### ISSUE TITLE
Dynamic Lighting does not affect handheld torches underwater.

### ISSUE THREAD

**Issue by 1upbyte** [LambdAurora/LambDynamicLights#38]
Without Torch
![image](https://user-images.githubusercontent.com/55856800/99157281-76cc1180-2695-11eb-9825-47c982554fa4.png)

With Torch
![image](https://user-images.githubusercontent.com/55856800/99157278-6f0c6d00-2695-11eb-95b6-8621d94b1525.png)

With Sea Lantern
![image](https://user-images.githubusercontent.com/55856800/99157306-9e22de80-2695-11eb-813c-526907313d34.png)

As you can see, torches do not work while in my hand while underwater.

**Comment by LambdAurora** [comment]
You can disable the "Water Sensitive" setting if you really want torch lighting up underwater.

Else it works as intended.
