### ISSUE TITLE
NullPointerException when respawning - potential incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by LemmaEOF** [LambdAurora/LambDynamicLights#39]
Minecraft: 1.16.4, Fabric
Immersive Portals: 0.43
LambDynamicLights: 1.3.2+1.16.4

When respawning (reproduced when respawning from the nether to the overworld), the game may crash from a series of errors, starting with a NullPointerException from LambDynamicLights, then failing `Validate.isTrue` inside Immersive Portals code at least once per tick, then finally crashing from a NullPointerException through an Immersive Portals redirect.

[crash log - errors start](https://paste.ee/p/f2Jy8#s=0&l=303) 
[crash log - game fuly crashes](https://paste.ee/p/f2Jy8#s=0&l=2976)

[multimc pack](https://ufile.io/xnc3y6nx)

**Comment by LambdAurora** [comment]
This is caused because LambDynamicLights tries to rebuild a chunk that is not in the same world/unloaded which some mods really doesn't like.

It's already on the TODO list of things to fix.

**Comment by LambdAurora** [comment]
Fixed in 1.3.3.
