### ISSUE TITLE
Mirrored Light Flickering (Immersive Portals)

### ISSUE THREAD

**Issue by nodogsleft** [LambdAurora/LambDynamicLights#44]
**Describe the bug**
When using the immersive portals mod, dynamic light sources will flicker when viewing a mirror object. Looking away will resume normal behaviour.

**To Reproduce**
1. Create a mirror by igniting glass with flint and steel
2. Hold any dynamic light source
3. Whether standing still or moving, the actual light source will flicker, which is seen on the side of the mirror as well

**Expected behavior**
Dynamic light source remains consistent on both sides of the mirror

**Screenshots**
It's difficult to show without video.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.16.4
 - Fabric Loader version [e.g. 0.10.6+build.214]
 - Mods: [lambdynamiclights-fabric-1.3.2+1.16.4, fabric-api-0.28.4+1.16, immersive-portals-0.54-mc1.16.4-fabric]
 - Version [e.g. 1.3.2]
 - Branch [e.g. mc1.16]

**Comment by LambdAurora** [comment]
This is most likely due to Immersive Portals' changes to the world renderer, I'm not even sure where to begin to fix that so, sadly, it will be likely for it to not be fixed.
