### ISSUE TITLE
Huge lag when igniting much tnt

### ISSUE THREAD

**Issue by luckymomohd** [LambdAurora/LambDynamicLights#45]
**Describe the bug**
When igniting a chain of tnt blocks it creates a huge lag dropping the fps to 0-2.

**To Reproduce**
1. Open up a world.
2. Place many tnt blocks (like /fill ~ ~ ~ ~50 ~ ~50 minecraft:tnt)
3. Ignite it and experience the lag.

**Expected behavior**
"Normal lag" or with Sodium absolute no lag.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.16.4
 - Fabric Loader version 0.10.8
 - Mods fabric-api-0.27.1 1.16, lambdynamiclights v1.3.2
 - Version 1.3.2
 - Branch mc1.16

**Additional context**
I tested it in my custom vanilla+ modpack (with sodium, lithium and phosphor) and standalone with fabricapi and dynamic lights. Both experience the same lag.

**Comment by LambdAurora** [comment]
The only thing I can recommend is to disable TNT dynamic lighting in LambDynamicLights.

The lag generated is sadly "expected" as it's a side-effect of the method used.
