### ISSUE TITLE
[Bug] Crash on World Leave

### ISSUE THREAD

**Issue by ZaneDragonBorn** [LambdAurora/LambDynamicLights#46]
**Describe the bug**
Whenever I Leave a world I will get a crash. This only happens when this mod has Dynamic Lighting enabled (Seems to also only happen when I have a torch or other light-based object

**To Reproduce**
1. Enter one of your worlds with The mod enabled
2. Have a Torch
3. Save & Quit to Title Screen
4. Crash time boiiis

**Expected behavior**
Do just go back to the title screen

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft 1.16.4
 - Fabric Loader version: 0.11.1
 - Mods: To many to list (Total of 236 mods Installed)
 - Version: 1.3.2
 - Branch: mc1.16?

**Additional context**
Below is the Crash
[crash-2021-01-16_20.03.55-client.txt](https://github.com/LambdAurora/LambDynamicLights/files/5825424/crash-2021-01-16_20.03.55-client.txt)
_I have also just noticed an update has released that may have fixed this issue. Still going to post it just in case_

**Comment by LambdAurora** [comment]
Please update to 1.3.3, the crash should not happen anymore.

**Comment by ZaneDragonBorn** [comment]
Ok, Thanks!
