### ISSUE TITLE
Crashing on startup with Modmenu and LambdaBetterGrass

### ISSUE THREAD

**Issue by sleepingdragoninn** [LambdAurora/LambDynamicLights#49]
**Describe the bug**
Startup crash

**To Reproduce**
1. Install Fabric API, Modmenu, LambdaBetterGrass, and LambDynamicLights (versions below)
2. Launch

**Screenshots**
![image](https://user-images.githubusercontent.com/55819817/104999763-81ce6400-5a81-11eb-8a20-b2e63f2d7f85.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft 1.16.4
 - Fabric Loader version 0.11.1
 - Mods: fabric-api-0.29.3+1.16, lambdabettergrass-fabric-1.0.1+1.16.3, modmenu-1.14.13+build.19
 - Version 1.3.4
 - Branch 1.16

**Additional context**
Figuring it's an issue with the latest updates (spruceui stuff?) - Confirmed occurs on 1.3.4 and 1.3.3, does not occur using 1.3.2

If there are any issues reproducing, let me know and I'll provide a full log.

**Comment by LambdAurora** [comment]
Please update [LambdaBetterGrass](https://github.com/LambdAurora/LambdaBetterGrass/releases/tag/1.0.2-1.16) (or via [modrinth](https://modrinth.com/mod/lambdabettergrass/version/5rHxiW08)).

**Comment by sleepingdragoninn** [comment]
Confirmed working with the update 👍
