### ISSUE TITLE
zh_cn.json

### ISSUE THREAD

**Issue by MarinaMarissa** [LambdAurora/LambDynamicLights#5]
[zh_cn.zip](https://github.com/LambdAurora/LambDynamicLights/files/4944804/zh_cn.zip)

**Comment by LambdAurora** [comment]
A Simplified Chinese translation already got included in latest commit: https://github.com/LambdAurora/LambDynamicLights/blob/mc1.16/src/main/resources/assets/lambdynlights/lang/zh_cn.json
It will be available in the next release.
