### ISSUE TITLE
LambdaControls incompatible with LambDynamicLights version 1.3.3 & above

### ISSUE THREAD

**Issue by oeramo** [LambdAurora/LambDynamicLights#50]
**Description of the bug**
I just updated MC to 1.16.5 and subsequently all the mods that I use to the latest versions, and by exclusion it seems like the latest release of LambDynamicLights (1.3.4) breaks the LambdaControls mod. The games launches as expected but, upon opening the controls options page to configure the input mode, a screen appears saying that it is saving the world, even thought I still didn't load one, before the game crashes. If I try to launch the game with the previous version of LambDynamicLights (1.3.2), the controls options page of LambdaControls loads as expected.

**To Reproduce**
1. Launch MC 1.16.5 with lambdynamiclights 1.3.4 & lambdacontrols 1.5.0
2. Click on Controls > Options
3. Game claims to be saving a world that still wasn't loaded, then crashes.

**Expected behavior**
Upon clicking on Controls > Options, I should be met with the LambdaControls page that allows to select and configure controllers and other input methods.

**Regression**
After testing it seems that the bug was introduced in LambDynamicLights 1.3.3. As mentioned above, v1.3.2 of the same mod makes LambdaControls work as expected. 

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Minecraft 1.16.5
 - Fabric 0.11.1
- <details>
    <summary>Mods:</summary>

   - Auto Config Updated API 3.3.1
   - Fabric API 0.29.3
   - LambdaControls 1.5.0
   - LambDynamicLights 1.3.4
   - Litematica 0.0.0-dev.20210112.155314
   - MaLiLib 0.10.0-dev.21+arne.2
   - MiniHUD 0.19.0-dev.20201103.184029
   - Mod Menu 1.14.13
   - Ok Zoomer 4.0.1
   - Phosphor 0.7.0
   - Sodium 0.1.0
   - Visual Overhaul 1.0.0
   - WorldEdit 7.2.2
</details>

 - Version 1.3.3 / 1.3.4
 - Branch: release

**Links to:**
https://github.com/LambdAurora/LambdaControls/issues/40

**Comment by LambdAurora** [comment]
I'm gonna to close this issue as the issue should be tracked on LambdAurora/LambdaControls#40.

I need to update LambdaControls, which will take fairly some time as there's a lot of stuff to change for the UI and other stuff

The main reason is just because LambDynamicLights updated with a new version of SpruceUI which is a breaking update because of a lot of internal rework.
