### ISSUE TITLE
Lamb dynamic lights conflicts with mod menu for fabric.

### ISSUE THREAD

**Issue by thm51b8f2d68cs** [LambdAurora/LambDynamicLights#53]
**Describe the bug**
Minecraft crashes at launch because of a mod conflict when both lamb dynamic lights and mod menu for fabric are together.

**To Reproduce**
1. Install lamb dynamic lights and mod menu both for fabric
2. Click on play
3. See error

**Expected behavior**
Minecraft launching with no problems

**Screenshots**
https://imgur.com/1a08l3y

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.16.5
 - Fabric Loader version 0.11.1
 - Mods fabric-api-0.30.0+1.16, lambdynamiclights-fabric-1.3.4+1.16, modmenu-1.10.5

**Additional context**
Nothing else to add.

**Comment by LambdAurora** [comment]
You have a very outdated version of ModMenu, please [update it](https://modrinth.com/mod/modmenu).

**Comment by thm51b8f2d68cs** [comment]
> You have a very outdated version of ModMenu, please [update it](https://modrinth.com/mod/modmenu).

Thank you.  It's weird that the curse forge would give me an outdated version but I updated and it is all working now.
