### ISSUE TITLE
[Bug] [Multiplayer-server exclusive?] Ghost lighting 

### ISSUE THREAD

**Issue by Flamingkitty** [LambdAurora/LambDynamicLights#56]
A persistent light with no source (Ghost light) was created while building a house on a multiplayer minecraft server. I created a small room with solid blocks (stone, wood logs), except for one wall which has barrels separating rooms. I covered the barrels and broke the soulsand to make sure no items were left behind, light remained. The light was coming from one corner and I made sure the light wasn't coming from myself. I filled in the entire space with cobblestone and dug it back out and the light remained. I left the server and reset my game- nope. I disabled only this mod and the issue was gone. I disabled all mods except for this mod and it's dependencies and the light re-appeared. Unable to recreate bug on singleplayer so far.

*Reproducing
Not entirely sure of cause. It happened after breaking a torch and having the item fall onto soul sand. There were slabs on the floor and upside-down stairs at some points along the wall. (again, made sure no item was left behind)

*Screenshot
![2021-02-26_12 58 20](https://user-images.githubusercontent.com/55114261/109331155-e32ce400-7832-11eb-98a1-01e46b08bca9.png)

*Desktop
 - Windows 10
 - Minecraft 1.16.5 (java 64x)
 - Fabric Loader version 0.11.1
 - Fabric-api v0.30.0+, lambdynamiclights v1.3.4, modmenu v1.16.7
 - Version [e.g. 1.3.2]
 - Branch mc1.16.5

*Hardware
CPU: AMD Ryzen 5 3600XT 6 core @ 3.79GHz
GPU: NVIDIA GeForce GTX 1060 6GB

**Comment by LambdAurora** [comment]
If it persists across restarts it's very likely still an entity that emits light.

The mod has a flaw that it doesn't check for walls, so dynamic lighting will pass through walls. The reason being I'm afraid it would be too laggy as it's already not the greatest thing performance wise.
