### ISSUE TITLE
This mod lags on fancy preset, but  OptiFine doesn't lag

### ISSUE THREAD

**Issue by luciobortoletto** [LambdAurora/LambDynamicLights#57]
**Describe the bug**
This mod lags on fancy preset, but te FPS are high.

**To Reproduce**
1. Load Minecraft with this mod
2. Set Dynamic Lights: Fancy
3. Play Minecraft with a torch in the hand
4. Lag, but the FPS are still high

**Expected behavior**
I expected not to lag.

**Screenshots**
I cannot make a screenshot, because the FPS are normal, but the game lags.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Minecraft 1.16.5
 - Fabric Loader version 0.11.2
 - Mods 
![Immagine 2021-02-27 210756](https://user-images.githubusercontent.com/52795018/109398913-e6fa5c80-793f-11eb-8f7d-ff51716654dd.png)

 - Version 1.3.4
 - Branch mc1.16

**Comment by machinesmith42** [comment]
link to video comparison?

**Comment by luciobortoletto** [comment]
Without using other mods (in the videos the "lag" is seen less ...):
LambDynamicLights https://mega.nz/file/rZwkyAaT#4dhV47kkT95us0n1FnNWKfJkGodroMxqO8kNQQ0eEBg

OptiFine https://mega.nz/file/WUhmHSJC#a-hyIkSmyAesD0NDPSacH4GYBLs_1tSLVPJpbFgwGuo

Sorry, but the files are too big for GitHub...

**Comment by LambdAurora** [comment]
Comparing a mod with the feature alone, and a mod with a bundle of features isn't fair.

The only reason it doesn't lag is OptiFine somehow makes chunk rebuild a bit faster.
You might want to try Sodium with Indium (note: it requires a fork of Sodium) so you can still use LambdaBetterGrass.

**Comment by luciobortoletto** [comment]
Ok, thanks for the info
