### ISSUE TITLE
Issue with the dropped torch item showing light through blocks

### ISSUE THREAD

**Issue by piemanau** [LambdAurora/LambDynamicLights#58]
The torch items light can go through blocks

1. Get a torch
2. Drop it in a concealed area

It shouldn't show any light at all like when you place it down inside the cube.

![image](https://user-images.githubusercontent.com/77601849/109699183-5b552a00-7be4-11eb-930d-3dfed78e8a46.png)
![image](https://user-images.githubusercontent.com/77601849/109699223-660fbf00-7be4-11eb-821e-65359c57a715.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.16.5
 - Fabric Loader version 0.11.2
 - Mods [e.g. fabric-api v0.25.1+build.416-1.16, lambdynamiclights v1.3.2, modmenu v1.14.6+build.31]
![image](https://user-images.githubusercontent.com/77601849/109699429-acfdb480-7be4-11eb-82d4-07f1e60fd3a2.png)
 - Version [e.g. 1.3.2] ?
 - Branch [e.g. mc1.16] ?

**Comment by LambdAurora** [comment]
Performances are already bad, fixing this issue would worsen the performances more.

**Comment by piemanau** [comment]
Ah ok cool

**Comment by bernards934** [comment]
Hello, I saw a similar feature on Lucent mod (on Forge Loader) and it was not that bad in term of performances.
Do you think this feature could maybe still be implemented behind a setting to toggle it ON or OFF ?
Doing it that way would ensure people can disable it in case of huge performance drop.
