### ISSUE TITLE
Doesn't Work With Latest Sodium Commits (If you were to compile a build yourself)

### ISSUE THREAD

**Issue by ghost** [LambdAurora/LambDynamicLights#6]
Title mostly saids it all, if you compile a build of sodium from the latest GitHub Repo the game will crash with this when trying to load a world:

https://pastebin.com/xN7ymAuC

Version 1.0 on curseforge works just fine.

And if you want to see the crash for yourself here is the latest build from compiling: (removed)

**Comment by LambdAurora** [comment]
I could not reproduce the same crash but I successfully produced another crash with the latest Sodium commit, the incompability will be hopefully fixed for next release.

**Comment by ghost** [comment]
Hmmm, the only other mods I had installed was phosphor, lithium, mod menu, and fabric api. Other than that, thanks for taking notice.

(Once it gets fixes I'll close the issue)

**Comment by LambdAurora** [comment]
So, with LambDynamicLights 1.3.0 this issue become a bit complicated.

Sodium for 1.16.2 isn't out and the one that will be available should be based off the development versions and not the current stable versions iirc, so hopefully the fix should apply to those future versions.

**Comment by ghost** [comment]
There are some unoffical 1.16.2 support branches of sodium but I don't know if it works with LambDynamicLights yet: https://github.com/jellysquid3/sodium-fabric/pull/250

**Comment by LambdAurora** [comment]
If it's based off the dev branches it should work, but unsure.

I prefer to wait for the *big refactor* before looking at it.

But the mixin should not be broken in theory.

**Comment by ghost** [comment]
I just tested with the unoffical 1.16.2 dev build (after compiling it) and LambDynamicLights work.

I used this fork: https://github.com/FlashyReese/sodium-fabric
