### ISSUE TITLE
Extreme fps drops from fire charges

### ISSUE THREAD

**Issue by Unstableclone** [LambdAurora/LambDynamicLights#64]
Extreme FPS drops while fighting blaze/in an area with lots of fire charges

To reproduce this simply spawn lots of blaze, or set up a line of dispensers full of fire charges

Without the mod, the large amount of fire charges barely have an impact on fps, almost unnoticeable, but with the mod enabled the frames can drop down to 30 or less

Here are my frames without the mod enabled (fps in top left)
![image](https://user-images.githubusercontent.com/85465468/120946781-a9118f00-c70b-11eb-9e41-baa384c050eb.png)

And here are my frames with the mod enabled (same setup and location)
![image](https://user-images.githubusercontent.com/85465468/120946814-c5153080-c70b-11eb-9f70-f2590de0c927.png)

 - OS: Windows 10 Home
 - Minecraft Version 1.16.5
 - Fabric Loader 0.11.3
 - Mods: just this one, however the bug still happens no matter what mods I have enabled, including sodium
 - Version 1.3.4
 - Branch mc 1.16

This effect may only be present on my pc but no matter what mods or configuration of mods I have, having this mod disabled causes no frame drops, and having it enabled causes extreme fps drops while fighting blaze

**Comment by Unstableclone** [comment]
While testing the mod out I realized that turning off dynamic lights for entities fixes the issue, but you also sacrifice dynamic lights from things like flame bows, maybe adding an option to enable/disable dynamic lights for certain entities (fire charges+others) would be a good fix?

**Comment by LambdAurora** [comment]
Latest commit, 2678e56, has introduced individual entities toggles, which will be included in the next release.
