### ISSUE TITLE
[1.17] Support for light block levels

### ISSUE THREAD

**Issue by Felix14-v2** [LambdAurora/LambDynamicLights#71]
Currently, the light blocks in the inventory that have different lighting levels glow with the same intensity (even with 0 level):
https://youtu.be/I33eF9vvEHA

it would be more logical if the level of dynamic light depended on the level of item in the inventory.

**Comment by LambdAurora** [comment]
Trying to fix this, but just for posterity, Java decided to become as cursed as possible.

![image](https://user-images.githubusercontent.com/12587332/127781193-3a16ea80-a513-4127-869f-cd3f95b4fca5.png)

Executing `state.getLuminance()` returns 7 as it should, but if the entire method is executed it returns magically 15.
