### ISSUE TITLE
Dynamic light for glow berries

### ISSUE THREAD

**Issue by FwuffyPetsOwO** [LambdAurora/LambDynamicLights#72]
**Is your feature request related to a problem? Please describe.**
It could be considered a bug that glow berries (which are light source blocks) are not used by LambDynamicLights

**Describe the solution you'd like**
Glow berries should function as dynamic light when in the player's (off)hand or in item entity form

**Describe alternatives you've considered**
I would like to know if this is possible with a resource pack or datapack for the time being until it is implemented in the mod.

**Additional context**
![2021-06-30_15 08 33](https://user-images.githubusercontent.com/65428450/124037986-47b0a900-d9b5-11eb-9780-0cf05bb3acf6.png)
![2021-06-30_15 08 24](https://user-images.githubusercontent.com/65428450/124038004-4ed7b700-d9b5-11eb-9a8d-76cd39ac2eb2.png)
![2021-06-30_15 08 59](https://user-images.githubusercontent.com/65428450/124038012-51d2a780-d9b5-11eb-9064-f40e515ac889.png)

**Comment by LambdAurora** [comment]
Will be added in the next update, in the meantime this can be fixed via a resource pack with the path `assets/<namespace>/dynamiclights/item/glow_berries.json`
and with content:
```json
{
  "item": "minecraft:blaze_rod",
  "luminance": 14
}
```
