### ISSUE TITLE
Enhancement for devs: API only LambDynamicLight verison

### ISSUE THREAD

**Issue by RuffleSteels** [LambdAurora/LambDynamicLights#77]
Today, I was trying to bundle LambDynamicLights with my mod, but as it depends on ModMenu, I will have to bundle ModMenu in my mod as well, which for compatibility is obviously not ideal. The reason I decided to bundle is because after days of trying to look through your code and the HOW_DOES_IT_WORK.md I could not get my entity to dynamically glow.

Could you make a api-only version of LambDynamicLights for mod devs to use as im sure a lot of other modders would really appreciate it. If this is not possible, a reply would be appreciated! Thanks for any help :P

**Comment by LambdAurora** [comment]
ModMenu is not required for the mod to work, if you bundle LDL you don't need to bundle ModMenu as well.
