### ISSUE TITLE
[Suggestion] Option to disable Dynamic Lights for glowing Item Frames

### ISSUE THREAD

**Issue by DarianLStephens** [LambdAurora/LambDynamicLights#79]
**Is your feature request related to a problem? Please describe.**
With the 1.17 addition of Glow Ink Sacs, I quite like the effect it gives for 'glow in the dark' items and text, especially combined with Charm's feature which allows you to make item frames invisible.
It's especially unnecessary because the Item Frames are permanent fixtures, and if you want them to emit light like a block, you can just place them on something that actually does emit light.

**Describe the solution you'd like**
I would like to see a config option to disable dynamic lighting on glowing Item Frames, or for this to be removed altogether to preserve the glow-in-the-dark feature.

**Describe alternatives you've considered**
Just dealing with the fact that they're now laggier, range-limited light blocks.
Or maybe using them in combination with Charm's invisible item frame feature to make fake invisible lights.

**Additional context**
![2021-09-05_08 06 20](https://user-images.githubusercontent.com/15375876/132109117-80e3c97e-96ae-46ff-96ba-1021a8bc3fea.png)
![2021-09-05_08 07 00](https://user-images.githubusercontent.com/15375876/132109118-1a40beb5-abee-4eff-a38e-8442b6714a85.png)

**Comment by rbits0** [comment]
I would love this feature too. I have made a quick modified version without glow item frame lighting in like 1 minute so you can use that in the mean time https://github.com/rbits0/LambDynamicLights/suites/4090478492/artifacts/104208943

**Comment by LambdAurora** [comment]
Individual entity toggles have been added in 2678e56, next release will include this change.

**Comment by LambdAurora** [comment]
Fixed in [1.2.0](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights/files/3541670).
