### ISSUE TITLE
Lagging while walking in Minecraft 1.18 with fancy dynamic light

### ISSUE THREAD

**Issue by EmanuelLopesS2** [LambdAurora/LambDynamicLights#91]
**To Reproduce**
1. Just have the mod loaded and walk with the dynamic light in fancy

**Expected behavior**
Not lagging

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.18
 - Fabric Loader version  0.12.6-1.18]
 - Mods fabric-api-0.43.1+1.18, cloth-config-6.0.42-fabric, lambdynamiclights-2.1.0+1.17, modmenu-3.0.0]
 - Version 1.18

it works fine with the fastest option

**Comment by LambdAurora** [comment]
Does this happen when not holding any light sources?
If you emit light, it's sadly a consequence of chunk rebuilding, I can't really do anything about this, you'll have to use Sodium once it's available.

**Comment by private-effort** [comment]
I have same issue even using sodium (mc1.18-0.4.0-alpha5)

**Comment by private-effort** [comment]
> I have same issue even using sodium (mc1.18-0.4.0-alpha5)

About 38 FPS when I'm holding and about 260 when I'm not holding

**Comment by private-effort** [comment]
> > I have same issue even using sodium (mc1.18-0.4.0-alpha5)
> 
> About 38 FPS when I'm holding and about 260 when I'm not holding

If this is not a problem of LamdDynamicLights, I hope it will be fixed in the stable version of sodium

**Comment by DerpDerpling** [comment]
Im also having this issue.

https://user-images.githubusercontent.com/57187871/144393553-13b4bd2f-029c-4f4c-b439-86053e78933b.mp4

 There's a video that shows it happening. Also heres my F3 Screen
![image](https://user-images.githubusercontent.com/57187871/144393742-46e03466-5a25-4f71-bd9d-70adc1e4ddf6.png)

It also seems to happen with normal light sources as well, like tnt, torches placed on the ground, light blocks, creepers, etc

**Comment by Juvenall** [comment]
> Does this happen when not holding any light sources?

Yup, this is the experience in my testing while running the Sodium alpha build for 1.18. If I'm holding any light source, I run into micro stuttering while moving. As soon as I put that source away, the stutters are gone. I've not noticed any issues, however, with entities that have been left on the ground.

**Comment by JonathanTippy** [comment]
> > Does this happen when not holding any light sources?
> 
> Yup, this is the experience in my testing while running the Sodium alpha build for 1.18. If I'm holding any light source, I run into micro stuttering while moving. As soon as I put that source away, the stutters are gone. I've not noticed any issues, however, with entities that have been left on the ground.

I'm having the same issue with LambDynamicLights v2.1.0+1.17 and sodium-fabric-mc1.18-0.4.0-alpha5+build.9

**Comment by ThatOmicron** [comment]
Same here. LambDynamicLights v2.1.0+1.17 and sodium-fabric-mc1.18-0.4.0-alpha5+build.9

**Comment by simonjonnemeth** [comment]
Honestly, I've been using Optifine and dynamic lighting for as long as I've been playing the game and have never noticed any drops in performance. There's an almost 80% FPS drop with your mod. That is excessive and unacceptable.

**Comment by Oliver-makes-code** [comment]
> Honestly, I've been using Optifine and dynamic lighting for as long as I've been playing the game and have never noticed any drops in performance. There's an almost 80% FPS drop with your mod. That is excessive and unacceptable.

Optifine and LambDynamicLights use different methods for creating dynamic lighting. Optifine uses a shader, while LDL rebuilds the chunk each time there's a movement. Chunk rebuilding is more expensive than a shader, but it's much easier to maintain.

**Comment by LambdAurora** [comment]
> > Honestly, I've been using Optifine and dynamic lighting for as long as I've been playing the game and have never noticed any drops in performance. There's an almost 80% FPS drop with your mod. That is excessive and unacceptable.
> 
> Optifine and LambDynamicLights use different methods for creating dynamic lighting. Optifine uses a shader, while LDL rebuilds the chunk each time there's a movement. Chunk rebuilding is more expensive than a shader, but it's much easier to maintain.

This is false, OptiFine and LambDynamicLights are using the same method: chunk rebuilds.
The only moment shader dynamic lighting is involved is when you actually involve a shader, that's all.

It's slow, yes. OptiFine either delays the chunk rebuild or optimizes something in the chunk rebuilding stack.
All I know is **I cannot modify the chunk rebuilding stack**, it's entirely out of scope for the mod, and would cause incompatibilities.

I've done testing with a bunch of moving lights recently, and I could not notice any FPS drop, there is something wrong somewhere.

@simonjonnemeth If you are using Sodium, **use Always Defer Chunk Updates: yes**, it fixed some of the FPS issues for some.

So, now before anyone else complains about the mod being slow, **post hardware info and mod list**, so that I can have actual data and no more claims in the void. I can't just guess stuff if all I get is "it doesn't work".

**Comment by simonjonnemeth** [comment]
> > > Honestly, I've been using Optifine and dynamic lighting for as long as I've been playing the game and have never noticed any drops in performance. There's an almost 80% FPS drop with your mod. That is excessive and unacceptable.
> > 
> > 
> > Optifine and LambDynamicLights use different methods for creating dynamic lighting. Optifine uses a shader, while LDL rebuilds the chunk each time there's a movement. Chunk rebuilding is more expensive than a shader, but it's much easier to maintain.
> 
> This is false, OptiFine and LambDynamicLights are using the same method: chunk rebuilds. The only moment shader dynamic lighting is involved is when you actually involve a shader, that's all.
> 
> It's slow, yes. OptiFine either delays the chunk rebuild or optimizes something in the chunk rebuilding stack. All I know is **I cannot modify the chunk rebuilding stack**, it's entirely out of scope for the mod, and would cause incompatibilities.
> 
> I've done testing with a bunch of moving lights recently, and I could not notice any FPS drop, there is something wrong somewhere.
> 
> @simonjonnemeth If you are using Sodium, **use Always Defer Chunk Updates: yes**, it fixed some of the FPS issues for some.
> 
> So, now before anyone else complains about the mod being slow, **post hardware info and mod list**, so that I can have actual data and no more claims in the void. I can't just guess stuff if all I get is "it doesn't work".

AMD Ryzen 9 5950X, Asus TUF RTX-3090 O24G

Minecraft 1.18.1

Mods:

Fabric API 0.44.0+1.18
FallingTree 2.16.1
Iris 1.1.3
Sodium 0.4.0-alpha5+build.9
Sodium Extra 0.3.7

**Comment by t0mtee** [comment]
Same here

**Comment by simonjonnemeth** [comment]
> Same here

Just so you know, I'm using Sildur's Enhanced Default shaders via Iris now, which, as of recently added support for handheld lighting which makes this mod obsolete for me. If you have the hardware for it, it runs perfectly well.

**Comment by LambdAurora** [comment]
Any "same here" response without any hardware details will be marked as off-topic now.

**Comment by baileyholl** [comment]
I am getting microstuttering as well with all dynamic light sources. The microstuttering stops set to fastest or fast.
I7-10700, Nvidia Geforce RTX 3070, 32GB/4gb allocated
https://spark.lucko.me/RkJd3wRgve
This is from a fresh gradle build from cloning this project. 

Edit:
Sorry, this appears to only be an issue for 1.17. I booted up an instance in GDLauncher for 1.18 and I am getting great performance now.

**Comment by Julienraptor01** [comment]
> @LambdAurora If you are using Sodium, use Always Defer Chunk Updates: yes, it fixed some of the FPS issues for some.

Sadly using ADCU has really bad side effects so even if it can be a temporary solution, it's not the final solution
I'll make vid on my main pc when i come back home
