### ISSUE TITLE
Glow Item Frames entities are missing

### ISSUE THREAD

**Issue by VeilStar** [LambdAurora/LambDynamicLights#92]
**Describe the bug**
Glow Item Frames aren't supported entities in the mod. They aren't in the entity list in the mod's settings and do not create a dynamic light under any circumstance, while their non-glowing counterpart, the regular old item frame can when a light emitting item is placed inside of it.

**Expected behavior**
Glow item frames should emit light by themselves (even without any items placed inside of them), and there should be an option for them in the mod's settings.

**Screenshots**
https://i.imgur.com/103kT6f.png
The left side is regular item frames, the right side is glow item frames. The top ones don't have an item in them, the bottom ones do. Only the regular item frame that is holding a sea lantern creates a dynamic light.

**Desktop (please complete the following information):**
 - Minecraft: 1.18
 - Fabric Loader version: 0.12.8-1.18
 - Mods: fabric-api-0.43.1+1.18, modmenu-3.0.0, lambdynamiclights-2.1.0+1.17

**Additional context**
Seems like a strange oversight given that glow squid and glow ink are a related entity and item that are supported. I have never used the mod in prior versions nor used prior versions of the mod before so I don't know if this is specific to the environment and version I'm using.

**Comment by LambdAurora** [comment]
There is a setting to enable it:
![image](https://user-images.githubusercontent.com/12587332/144503115-f88189df-0e6f-4b5d-b747-b9ff495638ef.png)

**Comment by VeilStar** [comment]
Right, apparently I am blind, my bad. Why is it not enabled by default though?
Edit: And is it intended that glow item frames don't give off light when held or are dropped as an item when having the setting enabled?

**Comment by LambdAurora** [comment]
> Right, apparently I am blind, my bad. Why is it not enabled by default though? Edit: And is it intended that glow item frames don't give off light when held or are dropped as an item when having the setting enabled?

It's not enabled by default because some other people complain that it emits light, and I kinda like that it's not emitting actual light by default, it can lead to nice effects.

The item never emitted light, this can be changed with a resource pack.
