### ISSUE TITLE
Dynamic light passes through tinted glass

### ISSUE THREAD

**Issue by Lumelore** [LambdAurora/LambDynamicLights#96]
To reproduce:
1. Build a room out of tinted glass. It should be dark inside.
2. Put a dynamic light nearby outside the room. It should stay dark in the room, however it does not.

Specs:
Windows 10 
Minecraft 1.18.1
Fabric loader version 0.12.11-1.18.1
fabric-api-0.44.0+1.18, lambdynamiclights-2.1.0+1.17, lithium-fabric-mc1.18.1-0.7.6, sodium-fabric-mc1.18-0.4.0-alpha5+build.9, modmenu-3.0.0

**Comment by 3meraldK** [comment]
bump @LambdAurora Tested on 1.19
