### ISSUE TITLE
Turning mod off automatically when shaders are active

### ISSUE THREAD

**Issue by janitor-raus** [LambdAurora/LambDynamicLights#99]
I reckon this wouldn't be difficult to implement, and could prove useful for some people. Currently the mod makes no distinction whether one runs custom shaders or not, but some of them offer dynamic lighting of their own for held items that works regardless of this mod.

As such, it might be a good idea to have a checkbox that would allow the user to have the mod automatically disable itself when a shader is active so that it would only work with the vanilla lighting system. Best of both worlds I think!

**Comment by LambdAurora** [comment]
There is now the ability to disable first-person dynamic lighting which I believe fixes this issue, or at least partly.

I do not wish to introduce an automatic turn off of the mod since not all shaders include dynamic lighting.
